# German - Germany

matecito_phrases+=(
  "Was mich nicht umbringt, macht mich stärker.|Friedrich Nietzsche"
  "Gott ist tot.|Friedrich Nietzsche"
  "Ohne Musik wäre das Leben ein Irrtum.|Friedrich Nietzsche"
  "Der Mensch ist etwas, das überwunden werden soll.|Friedrich Nietzsche"
  "Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.|Friedrich Nietzsche"
  "Das Leben ist kurz und die Wahrheit wirkt weit und lebt lange: sagen wir die Wahrheit.|Friedrich Nietzsche"
  "Der beste Weg, den Morgen vorauszusagen, ist, ihn zu erschaffen.|Friedrich Nietzsche"
  "Wer ein Warum zum Leben hat, erträgt fast jedes Wie.|Friedrich Nietzsche"
  "Im Individuum liegt die Kraft.|Friedrich Nietzsche"
  "Alles, was sich wiederholt, ist schwach.|Friedrich Nietzsche"
  "Das Geheimnis des größten Lebens ist, gefährlich zu leben.|Friedrich Nietzsche"
  "Man liebt zuletzt seine Begierde und nicht das Begehrte.|Friedrich Nietzsche"
  "Ich kenne mein Los. Einst wird sich an meinen Namen die Erinnerung von etwas Ungeheurem knüpfen.|Friedrich Nietzsche"
  "Die Kunst, glücklich zu sein, liegt in der Kunst, nichts zu bereuen.|Friedrich Nietzsche"
  "Das Glück des Denkenden ist ein Luxus.|Friedrich Nietzsche"
  "Jemand musste Josef K. verleumdet haben.|Franz Kafka"
  "Ein Buch muss die Axt sein für das gefrorene Meer in uns.|Franz Kafka"
  "Es gibt unendlich viel Hoffnung, aber nicht für uns.|Franz Kafka"
  "Im Kampf zwischen dir und der Welt, sekundiere der Welt.|Franz Kafka"
  "Wege entstehen dadurch, dass man sie geht.|Franz Kafka"
  "Das Schreiben ist eine Form des Gebetes.|Franz Kafka"
  "Man braucht keine Flügel zu haben, um fliegen zu können.|Franz Kafka"
  "Ich bin ein Ende oder ein Anfang.|Franz Kafka"
  "Der Mensch kann nicht leben ohne ein dauerndes Vertrauen in etwas Unzerstörbares in sich.|Franz Kafka"
  "Es gibt in der Welt nur wenige Dinge, die man für selbstverständlich halten kann.|Franz Kafka"
  "Die Sprache ist das Haus des Seins.|Martin Heidegger"
  "Das Dasein ist je meines.|Martin Heidegger"
  "Die Wissenschaft denkt nicht.|Martin Heidegger"
  "Fragen ist die Frömmigkeit des Denkens.|Martin Heidegger"
  "Die Zeit ist das, woraufhin das Dasein sich selbst versteht.|Martin Heidegger"
  "Es gibt nur einen wirklich ernsten philosophischen Problem: den Selbstmord.|Albert Camus (auf Deutsch)"
  "Zwei Dinge sind unendlich: das Universum und die menschliche Dummheit; aber beim Universum bin ich mir noch nicht sicher.|Albert Einstein"
  "Fantasie ist wichtiger als Wissen, denn Wissen ist begrenzt.|Albert Einstein"
  "Logik bringt dich von A nach B. Fantasie bringt dich überall hin.|Albert Einstein"
  "Das einzig Beständige ist die Veränderung.|Albert Einstein"
  "Stell dir vor, du hast gewonnen — dann beginne mit der Arbeit.|Albert Einstein"
  "Ein Mensch, der nie einen Fehler gemacht hat, hat nie etwas Neues ausprobiert.|Albert Einstein"
  "Die reinste Form des Wahnsinns ist, alles beim Alten zu lassen und zu hoffen, dass sich etwas ändert.|Albert Einstein"
  "Wenn du etwas erklären kannst, hast du es verstanden.|Albert Einstein"
  "Die Welt wird nicht bedroht von den Menschen, die böse sind, sondern von denen, die das Böse zulassen.|Albert Einstein"
  "Bildung ist das, was übrig bleibt, wenn man alles vergessen hat, was man in der Schule gelernt hat.|Albert Einstein"
  "Es ist leichter, einen Atomkern zu spalten als ein Vorurteil.|Albert Einstein"
  "Der Mensch ist nicht für die Niederlage geboren.|Albert Einstein"
  "Man soll denken lehren, nicht Gedanken.|Albert Einstein"
  "Alle Religionen, Künste und Wissenschaften sind Äste desselben Baumes.|Albert Einstein"
  "Wer aufhört, besser sein zu wollen, hat aufgehört, gut zu sein.|Oliver Cromwell (auf Deutsch)"
  "Leben bedeutet, Veränderung zu akzeptieren.|Johann Wolfgang von Goethe"
  "Alles Gescheite ist schon gedacht worden, man muss nur versuchen, es noch einmal zu denken.|Johann Wolfgang von Goethe"
  "Wo viel Licht ist, ist starker Schatten.|Johann Wolfgang von Goethe"
  "Es ist nicht genug zu wissen, man muss auch anwenden; es ist nicht genug zu wollen, man muss auch tun.|Johann Wolfgang von Goethe"
  "Man reist nicht, um anzukommen, sondern um zu reisen.|Johann Wolfgang von Goethe"
  "Wer nicht neugierig ist, erfährt nichts.|Johann Wolfgang von Goethe"
  "Das Beste an guten Freunden ist nicht ihre Hilfe, sondern das Wissen, dass man sich auf sie verlassen kann.|Johann Wolfgang von Goethe"
  "Wer die Freiheit aufgibt, um Sicherheit zu gewinnen, wird am Ende beides verlieren.|Johann Wolfgang von Goethe"
  "Der Mensch irrt, solange er strebt.|Johann Wolfgang von Goethe"
  "Behandle die Menschen so, als wären sie, was sie sein sollten, und du hilfst ihnen zu werden, was sie sein können.|Johann Wolfgang von Goethe"
  "Das Leben gehört den Lebendigen an, und wer lebt, muss auf Wechsel gefasst sein.|Johann Wolfgang von Goethe"
  "In der Kunst und im Leben ist alles zu ertragen, nur nicht eine Reihe von schönen Tagen.|Johann Wolfgang von Goethe"
  "Man kann einen Menschen nichts lehren, man kann ihm nur helfen, es in sich selbst zu entdecken.|Johann Wolfgang von Goethe"
  "Wer immer strebend sich bemüht, den können wir erlösen.|Johann Wolfgang von Goethe"
  "Die Wahrheit muss immer wiederholt werden.|Johann Wolfgang von Goethe"
  "Das Schwierigste ist nicht, die neuen Ideen zu akzeptieren, sondern die alten zu vergessen.|John Maynard Keynes (auf Deutsch)"
  "Wenn die Tatsachen sich ändern, ändere ich meine Meinung.|John Maynard Keynes (auf Deutsch)"
  "Wer nicht wagt, der nicht gewinnt.|Deutsches Sprichwort"
  "Übung macht den Meister.|Deutsches Sprichwort"
  "Ende gut, alles gut.|Deutsches Sprichwort"
  "Morgenstund hat Gold im Mund.|Deutsches Sprichwort"
  "Was du heute kannst besorgen, das verschiebe nicht auf morgen.|Deutsches Sprichwort"
  "Gut Ding will Weile haben.|Deutsches Sprichwort"
  "Wer anderen eine Grube gräbt, fällt selbst hinein.|Deutsches Sprichwort"
  "Der Apfel fällt nicht weit vom Stamm.|Deutsches Sprichwort"
  "Wenn zwei sich streiten, freut sich der Dritte.|Deutsches Sprichwort"
  "Lügen haben kurze Beine.|Deutsches Sprichwort"
  "Alle guten Dinge sind drei.|Deutsches Sprichwort"
  "Zeit ist Geld.|Deutsches Sprichwort"
  "Wer zuletzt lacht, lacht am besten.|Deutsches Sprichwort"
  "Das ist mir Wurst.|Deutsches Sprichwort"
  "Der frühe Vogel fängt den Wurm.|Deutsches Sprichwort"
  "Musik ist die Sprache der Gefühle.|Immanuel Kant"
  "Handle nur nach derjenigen Maxime, durch die du zugleich wollen kannst, dass sie ein allgemeines Gesetz werde.|Immanuel Kant"
  "Zwei Dinge erfüllen das Gemüt mit immer neuer Bewunderung: der bestirnte Himmel über mir und das moralische Gesetz in mir.|Immanuel Kant"
  "Der Mensch ist frei, aber überall in Ketten.|Immanuel Kant"
  "Wage es, weise zu sein!|Immanuel Kant"
  "Aufklärung ist der Ausgang des Menschen aus seiner selbst verschuldeten Unmündigkeit.|Immanuel Kant"
  "Gedanken ohne Inhalt sind leer, Anschauungen ohne Begriffe sind blind.|Immanuel Kant"
  "Es ist nicht genug, dass man Recht hat; man muss es auch sagen dürfen.|Immanuel Kant"
  "Der Verstand schreibt der Natur die Gesetze vor.|Immanuel Kant"
  "Glückseligkeit ist nicht ein Ideal der Vernunft, sondern der Einbildungskraft.|Immanuel Kant"
  "Wir sehen die Dinge nicht, wie sie sind, sondern wie wir sind.|Anaïs Nin (auf Deutsch)"
  "In jedem Ende liegt ein Anfang.|Deutsches Sprichwort"
  "Reden ist Silber, Schweigen ist Gold.|Deutsches Sprichwort"
  "Alles hat ein Ende, nur die Wurst hat zwei.|Deutsches Sprichwort"
  "Heimat ist da, wo man verstanden wird.|Deutsches Sprichwort"
  "Der Klügere gibt nach.|Deutsches Sprichwort"
  "Ohne Fleiß kein Preis.|Deutsches Sprichwort"
  "Wer rastet, der rostet.|Deutsches Sprichwort"
  "Jedem das Seine.|Deutsches Sprichwort"
  "Ordnung ist das halbe Leben.|Deutsches Sprichwort"
)
