# French - France

matecito_phrases+=(
  "Au milieu de l'hiver, j'ai découvert en moi un invincible été.|Albert Camus"
  "Il faut imaginer Sisyphe heureux.|Albert Camus"
  "La liberté, c'est n'avoir pas peur.|Albert Camus"
  "Mal nommer les choses, c'est ajouter au malheur du monde.|Albert Camus"
  "L'absurde naît de la confrontation entre le besoin humain et le silence déraisonnable du monde.|Albert Camus"
  "Le vrai courage, c'est de préférer le bonheur à la raison.|Albert Camus"
  "Aimer un être, c'est accepter de vieillir avec lui.|Albert Camus"
  "La vérité mystérieuse, c'est que l'art vit de contraintes et meurt de liberté.|Albert Camus"
  "Je me révolte, donc nous sommes.|Albert Camus"
  "Nous sommes tous des cas particuliers.|Albert Camus"
  "Sans la culture et la liberté relative qu'elle suppose, la société est une jungle.|Albert Camus"
  "La vraie générosité envers l'avenir consiste à tout donner au présent.|Albert Camus"
  "L'homme absurde ne se suicide pas.|Albert Camus"
  "Le bonheur et l'absurde sont deux fils de la même terre.|Albert Camus"
  "Il n'y a qu'un problème philosophique vraiment sérieux: c'est le suicide.|Albert Camus"
  "L'enfer, c'est les autres.|Jean-Paul Sartre"
  "L'existence précède l'essence.|Jean-Paul Sartre"
  "L'homme est condamné à être libre.|Jean-Paul Sartre"
  "La conscience est un être pour lequel il est dans son être question de son être.|Jean-Paul Sartre"
  "On ne naît pas femme: on le devient.|Simone de Beauvoir"
  "Se libérer, c'est assumer la liberté des autres.|Simone de Beauvoir"
  "La femme n'est pas faite, elle se fait.|Simone de Beauvoir"
  "Ce n'est pas votre sexe qui vous définit, c'est ce que vous en faites.|Simone de Beauvoir"
  "Je suis trop intelligente pour me laisser gouverner par les émotions.|Simone de Beauvoir"
  "L'amour véritable est celui qui s'accompagne de liberté.|Simone de Beauvoir"
  "Il faut vivre pleinement et sans regrets.|Simone de Beauvoir"
  "La liberté ne se donne pas, elle se prend.|Simone de Beauvoir"
  "On ne connaît jamais vraiment quelqu'un.|Simone de Beauvoir"
  "Le courage, c'est de chercher la vérité et de la dire.|Simone de Beauvoir"
  "Je pense, donc je suis.|René Descartes"
  "Le bon sens est la chose du monde la mieux partagée.|René Descartes"
  "La lecture de tous les bons livres est comme une conversation avec les plus honnêtes gens des siècles passés.|René Descartes"
  "Pour examiner la vérité, il est besoin, une fois dans sa vie, de mettre toutes choses en doute autant qu'on le peut.|René Descartes"
  "Il n'est pas suffisant d'avoir l'esprit bon, mais le principal est de l'appliquer bien.|René Descartes"
  "La philosophie est la base de toutes les autres sciences.|René Descartes"
  "Le doute est le commencement de la sagesse.|René Descartes"
  "Pour atteindre la vérité, il faut douter de tout ce qu'on a appris.|René Descartes"
  "L'admiration est la première de toutes les passions.|René Descartes"
  "Les grandes âmes ont de la volonté; les faibles n'ont que des désirs.|René Descartes"
  "Les hommes naissent et demeurent libres et égaux en droits.|Voltaire"
  "Le mieux est l'ennemi du bien.|Voltaire"
  "Il faut cultiver notre jardin.|Voltaire"
  "Chaque homme est coupable du bien qu'il n'a pas fait.|Voltaire"
  "La superstition est à la religion ce que l'astrologie est à l'astronomie.|Voltaire"
  "Dieu a fait l'homme à son image et l'homme le lui a bien rendu.|Voltaire"
  "L'art de la médecine consiste à amuser le malade pendant que la nature le guérit.|Voltaire"
  "Le paradis terrestre est où je suis.|Voltaire"
  "Trop de choses finissent.|Voltaire"
  "Qui n'a pas l'esprit de son âge, de son âge a tous les malheurs.|Voltaire"
  "La vie, c'est ce qui vous arrive pendant que vous êtes occupé à faire d'autres projets.|Victor Hugo"
  "Aimer, c'est agir.|Victor Hugo"
  "On résiste à l'invasion des armées; on ne résiste pas à l'invasion des idées.|Victor Hugo"
  "Les utopies d'aujourd'hui sont les réalités de demain.|Victor Hugo"
  "Celui qui ouvre une porte d'école, ferme une prison.|Victor Hugo"
  "La musique, c'est du bruit qui pense.|Victor Hugo"
  "Le rire, c'est le soleil; il chasse l'hiver du visage humain.|Victor Hugo"
  "La mort n'est pas une fin, c'est un commencement.|Victor Hugo"
  "Rien n'est plus fort qu'une idée dont le temps est venu.|Victor Hugo"
  "Dieu, c'est le rêve de l'homme.|Victor Hugo"
  "La vérité vaut bien qu'on passe quelques années sans la trouver.|Jules Renard"
  "Être libre, c'est rester soi-même.|Jules Renard"
  "L'amour, c'est l'espace et le temps rendus sensibles au cœur.|Marcel Proust"
  "Le vrai voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.|Marcel Proust"
  "On ne reçoit pas la sagesse, il faut la découvrir soi-même après un trajet que personne ne peut faire pour nous.|Marcel Proust"
  "La mémoire involontaire est plus fidèle que la mémoire volontaire.|Marcel Proust"
  "Les vrais paradis sont les paradis qu'on a perdus.|Marcel Proust"
  "Longtemps, je me suis couché de bonne heure.|Marcel Proust"
  "Il n'y a pas de grandeur là où il n'y a pas de simplicité.|Marcel Proust"
  "Le bonheur, c'est le désir qui se souvient.|Marcel Proust"
  "On devient moral dès qu'on est malheureux.|Marcel Proust"
  "L'amour est une forme de préjugé favorable envers soi-même.|Marcel Proust"
  "Je n'ai pas peur des tempêtes, car j'apprends à naviguer mon vaisseau.|Jules Verne"
  "La science, mon garçon, est faite d'erreurs, mais d'erreurs qu'il est bon de commettre.|Jules Verne"
  "Ce que l'un a découvert, l'autre peut le faire.|Jules Verne"
  "Tout ce qu'un homme est capable d'imaginer, d'autres hommes seront capables de le réaliser.|Jules Verne"
  "La Terre ne manque pas de belles choses.|Jules Verne"
  "La liberté d'esprit est la plus précieuse des libertés.|Jules Verne"
  "La femme est toujours mystérieuse.|Gustave Flaubert"
  "Lire pour vivre.|Gustave Flaubert"
  "La parole est une machine à amplifier les malentendus.|Gustave Flaubert"
  "Ce que l'on conçoit bien s'énonce clairement.|Nicolas Boileau"
  "Il n'est point de serpent ni de monstre odieux qui par l'art imité ne puisse plaire aux yeux.|Nicolas Boileau"
  "Hâtez-vous lentement; et, sans perdre courage, vingt fois sur le métier remettez votre ouvrage.|Nicolas Boileau"
  "Avant donc que d'écrire, apprenez à penser.|Nicolas Boileau"
  "La critique est aisée et l'art est difficile.|Philippe Néricault Destouches"
  "Le temps c'est de l'argent.|Proverbe français"
  "Mieux vaut tard que jamais.|Proverbe français"
  "L'appétit vient en mangeant.|François Rabelais"
  "Science sans conscience n'est que ruine de l'âme.|François Rabelais"
  "Fais ce que tu voudras.|François Rabelais"
  "Nul n'est prophète en son pays.|Proverbe français"
  "Paris vaut bien une messe.|Henri IV"
  "L'État, c'est moi.|Louis XIV"
  "Le style, c'est l'homme même.|Georges-Louis Leclerc de Buffon"
  "La clarté est la politesse de ceux qui ont quelque chose à dire.|Jules Renard"
  "Tout ce qui est excessif est insignifiant.|Charles-Maurice de Talleyrand"
  "La France est un pays où tout le monde cherche à abattre le gouvernement.|Charles de Gaulle"
  "La vieillesse est un naufrage.|Charles de Gaulle"
  "La gloire se donne seulement à ceux qui l'ont toujours rêvée.|Charles de Gaulle"
)
