# Spanish - Argentina

matecito_phrases+=(
  "Siempre imaginé que el paraíso sería algún tipo de biblioteca.|Jorge Luis Borges"
  "Uno no es lo que es por lo que escribe, sino por lo que ha leído.|Jorge Luis Borges"
  "El original es infiel a la traducción.|Jorge Luis Borges"
  "La duda es uno de los nombres de la inteligencia.|Jorge Luis Borges"
  "El tiempo es la sustancia de la que estoy hecho.|Jorge Luis Borges"
  "Nada se edifica sobre la piedra, todo sobre la arena.|Jorge Luis Borges"
  "Que otros se jacten de las páginas que han escrito; a mí me enorgullecen las que he leído.|Jorge Luis Borges"
  "Somos nuestra memoria, somos ese quimérico museo de formas inconstantes.|Jorge Luis Borges"
  "El verbo leer, como el verbo amar, no soporta el modo imperativo.|Jorge Luis Borges"
  "La literatura no es otra cosa que un sueño dirigido.|Jorge Luis Borges"
  "He cometido el peor de los pecados que un hombre puede cometer: no he sido feliz.|Jorge Luis Borges"
  "El olvido es la única venganza y el único perdón.|Jorge Luis Borges"
  "Uno está enamorado cuando se da cuenta de que otra persona es única.|Jorge Luis Borges"
  "La muerte es una vida vivida. La vida es una muerte que viene.|Jorge Luis Borges"
  "Si el honor fuera de este mundo, me sentiría ultrajado.|Jorge Luis Borges"
  "Cualquier destino consta de un solo momento: el momento en que el hombre sabe para siempre quién es.|Jorge Luis Borges"
  "La democracia es un abuso de la estadística.|Jorge Luis Borges"
  "La realidad no es siempre probable ni verosímil.|Jorge Luis Borges"
  "Pensar es olvidar diferencias, es generalizar, abstraer.|Jorge Luis Borges"
  "La belleza es ese misterio hermoso que no descifran ni la psicología ni la retórica.|Jorge Luis Borges"
  "Andábamos sin buscarnos pero sabiendo que andábamos para encontrarnos.|Julio Cortázar"
  "Nada está perdido si se tiene el valor de proclamar que todo está perdido.|Julio Cortázar"
  "La explicación es un error bien vestido.|Julio Cortázar"
  "Cada vez que me preguntan por qué escribo, respondo que no lo sé.|Julio Cortázar"
  "Las palabras nunca alcanzan cuando lo que hay que decir desborda el alma.|Julio Cortázar"
  "Nada mata tanto a un hombre como la obligación de ser feliz.|Julio Cortázar"
  "Después de todo, la muerte es solo un síntoma de que hubo vida.|Julio Cortázar"
  "Los libros van siendo el único lugar de la casa donde todavía se puede estar tranquilo.|Julio Cortázar"
  "La música piensa mientras suena.|Julio Cortázar"
  "La costumbre es la muerte de la sorpresa.|Julio Cortázar"
  "Solo viviendo absurdamente se podría romper alguna vez este absurdo infinito.|Julio Cortázar"
  "Todos los fuegos el fuego.|Julio Cortázar"
  "Nada es más complicado que pedirle a un contemporáneo que te entienda.|Julio Cortázar"
  "El amor, esa palabra.|Julio Cortázar"
  "Hay metáforas que son más reales que la gente que anda por la calle.|Julio Cortázar"
  "Es tan fácil pasar por alto a los demás, tan fácil ignorarlos.|Ernesto Sabato"
  "La vida es una herida absurda.|Cátulo Castillo"
  "Nada es más peligroso que una idea cuando no se tiene más que una.|Ernesto Sabato"
  "El hombre es una mezcla de grandeza y miseria.|Ernesto Sabato"
  "La esperanza es una invención de los desesperados.|Ernesto Sabato"
  "Habrá siempre un hombre tal que, aunque su mundo se derrumbe, se la jugará por una causa.|Ernesto Sabato"
  "Vivir consiste en construir futuros recuerdos.|Ernesto Sabato"
  "El amor verdadero es un acto de coraje.|Ernesto Sabato"
  "La lucidez suele ser el castigo de los que ven demasiado.|Ernesto Sabato"
  "El infierno está en nosotros mismos.|Ernesto Sabato"
  "El mundo nada puede contra un hombre que canta en la miseria.|Ernesto Sabato"
  "Nada grande se hace sin pasión.|Ernesto Sabato"
  "La única manera de salvarnos es la creación.|Ernesto Sabato"
  "El hombre se realiza en la medida en que se compromete.|Ernesto Sabato"
  "La amistad es una pasión tranquila.|Adolfo Bioy Casares"
  "El mundo atribuye sus fracasos a la mala suerte.|Adolfo Bioy Casares"
  "La literatura es una forma de felicidad.|Adolfo Bioy Casares"
  "Las cosas más importantes son las que uno no dice.|Adolfo Bioy Casares"
  "La memoria es una forma del olvido.|Adolfo Bioy Casares"
  "El pasado es siempre una invención del presente.|Adolfo Bioy Casares"
  "No hay placer comparable al de encontrar palabras nuevas.|Adolfo Bioy Casares"
  "El azar es el seudónimo de Dios cuando no quiere firmar.|Adolfo Bioy Casares"
  "La realidad suele ser una mala imitación de la ficción.|Adolfo Bioy Casares"
  "Los recuerdos no pueblan nuestra soledad; la hacen más profunda.|Adolfo Bioy Casares"
  "La felicidad es una tarea que nunca termina.|Adolfo Bioy Casares"
  "El genio es una infinita capacidad de trabajo.|Leopoldo Lugones"
  "La patria es un acto de fe.|Leopoldo Lugones"
  "La poesía es la expresión más alta del pensamiento humano.|Leopoldo Lugones"
  "La imaginación es la única arma en la guerra contra la realidad.|Leopoldo Lugones"
  "El idioma es la sangre del espíritu.|Leopoldo Lugones"
  "Las palabras tienen alma.|Leopoldo Lugones"
  "La tradición no es culto de cenizas, sino custodia del fuego.|Leopoldo Lugones"
  "La inteligencia sin carácter no sirve para nada.|Leopoldo Lugones"
  "Las ideas no se matan.|Domingo Faustino Sarmiento"
  "Bárbaros, las ideas no se degüellan.|Domingo Faustino Sarmiento"
  "Todos los problemas son problemas de educación.|Domingo Faustino Sarmiento"
  "Hombre, pueblo, Nación, Estado: todo está en los humildes bancos de la escuela.|Domingo Faustino Sarmiento"
  "La escuela es la base de la civilización.|Domingo Faustino Sarmiento"
  "Educar al soberano es asegurar la libertad.|Domingo Faustino Sarmiento"
  "Un pueblo ignorante siempre será instrumento de su propia destrucción.|Domingo Faustino Sarmiento"
  "El futuro es nuestro por prepotencia de trabajo.|Roberto Arlt"
  "El hombre honrado no tiene casi nunca dinero.|Roberto Arlt"
  "El fracaso es la condición del éxito.|Roberto Arlt"
  "La vida es dura y hay que ponerle coraje.|Roberto Arlt"
  "No hay peor miseria que la de un hombre solo.|Roberto Arlt"
  "El sufrimiento es la base del conocimiento.|Roberto Arlt"
  "Se vive para trabajar o se trabaja para vivir, pero siempre se trabaja.|Roberto Arlt"
  "La única verdad es la realidad.|Juan Domingo Perón"
  "La literatura es una forma de espionaje.|Manuel Puig"
  "El cine me enseñó a sentir.|Manuel Puig"
  "La nostalgia es una forma de resistencia.|Manuel Puig"
  "Los sueños son la verdadera vida.|Manuel Puig"
  "La cultura popular también es cultura.|Manuel Puig"
  "La literatura trabaja con lo que no se puede decir.|Ricardo Piglia"
  "Un crítico es alguien que narra sus lecturas.|Ricardo Piglia"
  "Toda ficción encierra una teoría del mundo.|Ricardo Piglia"
  "La verdad tiene la estructura de una ficción.|Ricardo Piglia"
  "Escribir es intentar pensar de otro modo.|Ricardo Piglia"
  "La literatura no refleja la realidad, la construye.|Juan José Saer"
  "El presente es siempre una reconstrucción del pasado.|Juan José Saer"
  "Narrar es una forma de explorar el tiempo.|Juan José Saer"
  "La memoria deforma lo que recuerda.|Juan José Saer"
  "La jaula se ha vuelto pájaro y se ha volado.|Alejandra Pizarnik"
  "El silencio es cierto.|Alejandra Pizarnik"
  "Escribir un poema es reparar la herida fundamental.|Alejandra Pizarnik"
  "La palabra que sana es la que sangra.|Alejandra Pizarnik"
  "Todo hace el amor con el silencio.|Alejandra Pizarnik"
  "La imaginación es el reino donde todo es posible.|Silvina Ocampo"
  "Lo extraño es cotidiano si se lo sabe mirar.|Silvina Ocampo"
  "Los sueños dicen más que la vigilia.|Silvina Ocampo"
  "La infancia es un territorio sagrado.|Silvina Ocampo"
  "Escribo para descubrir lo que no sé.|Silvina Ocampo"
  "No soy un pesimista, soy un optimista mal informado.|Roberto Fontanarrosa"
  "El fútbol es lo más importante de las cosas menos importantes.|Roberto Fontanarrosa"
  "Hay cosas que no se pueden explicar, solo sentir.|Roberto Fontanarrosa"
  "El humor es una actitud ante la vida.|Roberto Fontanarrosa"
  "¿No será que en este mundo hay cada vez más gente y menos personas?|Quino"
  "Lo urgente no deja tiempo para lo importante.|Quino"
  "El mundo está lleno de gente dispuesta a solucionar problemas que no tiene.|Quino"
  "El hombre es tierra que anda.|Atahualpa Yupanqui"
  "Las penas son de nosotros, las vaquitas son ajenas.|Atahualpa Yupanqui"
  "El silencio es la música del alma.|Atahualpa Yupanqui"
  "El que no se anima a volar, se queda mirando.|María Elena Walsh"
  "La libertad es una costumbre.|María Elena Walsh"
  "Los chicos no son el futuro, son el presente.|María Elena Walsh"
  "La nostalgia es la censura de la memoria.|Osvaldo Soriano"
  "Uno siempre vuelve a los lugares donde fue feliz.|Osvaldo Soriano"
  "El fútbol es la patria en pantalones cortos.|Osvaldo Soriano"
  "La vida es corta, pero el día es largo.|Alejandro Dolina"
  "El amor es una forma de coraje.|Alejandro Dolina"
  "La felicidad es episódica.|Alejandro Dolina"
  "La amistad es el único lujo que uno no puede dejar de darse.|Alejandro Dolina"
  "Mañana es mejor.|Luis Alberto Spinetta"
  "La música es la forma más directa de llegar al alma.|Luis Alberto Spinetta"
  "Tú me quieres blanca, tú me quieres casta.|Alfonsina Storni"
  "Bien pudiera ser que todo lo que en verso he sentido no fuera más que aquello que nunca pudo ser.|Alfonsina Storni"
  "El alma es una llamarada.|Alfonsina Storni"
  "Quien no llora, no mama.|Enrique Santos Discépolo"
  "Hoy resulta que es lo mismo ser derecho que traidor.|Enrique Santos Discépolo"
  "Que el mundo fue y será una porquería, ya lo sé.|Enrique Santos Discépolo"
  "Los hermanos sean unidos porque esa es la ley primera.|José Hernández"
  "Con la democracia se come, se cura y se educa.|Raúl Alfonsín"
  "Donde hay una necesidad, nace un derecho.|Eva Perón"
  "Volveré y seré millones.|Eva Perón"
  "La educación es el futuro de los pueblos.|René Favaloro"
  "El verdadero éxito es hacer lo que uno ama.|René Favaloro"
  "La ciencia no tiene fronteras.|César Milstein"
  "La poesía es un acto de amor.|Juan Gelman"
  "Escribo para no morir de silencio.|Juan Gelman"
  "Se miran, se presienten, se desean.|Oliverio Girondo"
  "Hay que romper con todo.|Oliverio Girondo"
  "No se puede vivir sin dignidad.|Rodolfo Walsh"
  "La cultura es un derecho, no un privilegio.|Victoria Ocampo"
  "La libertad es la condición de toda creación.|Victoria Ocampo"
  "Pensar es atreverse a estar loco.|Enrique Pichón-Rivière"
  "Los ideales son la brújula del espíritu.|José Ingenieros"
  "La moral está en la conciencia, no en los códigos.|José Ingenieros"
  "Argentina es un país de paradojas.|Ezequiel Martínez Estrada"
  "La soledad es la patria del fuerte.|Ezequiel Martínez Estrada"
  "Sur, paredón y después.|Homero Manzi"
  "Pensar es un acto revolucionario.|Arturo Jauretche"
  "La civilización y la barbarie no se excluyen.|Lucio V. Mansilla"
  "Todo lo que puede ser imaginado es real.|Macedonio Fernández"
  "Escribir es seguir adelante sin saber adónde se va.|César Aira"
  "Gracias totales.|Gustavo Cerati"
  "Mereces lo que sueñas.|Gustavo Cerati"
  "No me dejan salir.|Charly García"
  "Los dinosaurios van a desaparecer.|Charly García"
  "La cultura es lo único que puede salvar a un pueblo.|Mercedes Sosa"
  "La música debe emocionar antes que explicar.|Astor Piazzolla"
  "La ciencia ficción es el presente del futuro.|Héctor Germán Oesterheld"
  "La pelota no se mancha.|Diego Armando Maradona"
)
