# Spanish - Chile

matecito_phrases+=(
  "Para que nada nos separe, que nada nos una.|Pablo Neruda"
  "Es tan corto el amor, y es tan largo el olvido.|Pablo Neruda"
  "Podrán cortar todas las flores, pero no podrán detener la primavera.|Pablo Neruda"
  "Queda prohibido no sonreír a los problemas, no luchar por lo que quieres.|Pablo Neruda"
  "Donde haya un árbol que plantar, plántalo tú. Donde haya un error que enmendar, enmiéndalo tú.|Gabriela Mistral"
  "El futuro de los niños es siempre hoy. Mañana será tarde.|Gabriela Mistral"
  "La educación es, tal vez, la forma más alta de buscar a Dios.|Gabriela Mistral"
  "Lo que el alma hace por su cuerpo es lo que el artista hace por su pueblo.|Gabriela Mistral"
  "Creer que un cielo azul es el cielo, es un error.|Nicanor Parra"
  "La izquierda y la derecha unidas jamás serán vencidas.|Nicanor Parra"
  "USA donde la libertad es una estatua.|Nicanor Parra"
  "Dime cuáles son para ti las cosas más importantes y te diré quién eres.|Nicanor Parra"
  "El poeta es un pequeño Dios.|Vicente Huidobro"
  "Inventa mundos nuevos y cuida tu palabra; el adjetivo, cuando no da vida, mata.|Vicente Huidobro"
  "Hacer un poema es como hacer un viaje.|Vicente Huidobro"
  "La literatura es un oficio peligroso.|Roberto Bolaño"
  "Escribir no es normal. Lo normal es leer.|Roberto Bolaño"
  "Uno nunca termina de leer, aunque los libros se acaben.|Roberto Bolaño"
  "La memoria es un espejo que miente.|Roberto Bolaño"
  "La biblioteca es un archivo de la felicidad.|Isabel Allende"
  "La muerte no existe, la gente solo muere cuando la olvidan.|Isabel Allende"
  "Memoria selectiva para recordar lo bueno, prudencia lógica para no arruinar el presente.|Isabel Allende"
  "No existe la felicidad absoluta, solo momentos de alegría que te salvan la vida.|Isabel Allende"
  "Escribir es como un matrimonio: se empieza con amor y se termina con una paciencia infinita.|Alejandro Jodorowsky"
  "Lo que das, te lo das. Lo que no das, te lo quitas.|Alejandro Jodorowsky"
  "Haz de tu vida un sueño y de tu sueño una realidad.|Alejandro Jodorowsky"
  "La vida es una obra de teatro que no permite ensayos.|Alejandro Jodorowsky"
  "Si te das cuenta de que eres un esclavo, ya dejas de serlo.|Alejandro Jodorowsky"
  "La soledad es el único lugar donde no se miente.|Pedro Lemebel"
  "No necesito que me acepten, necesito que me respeten.|Pedro Lemebel"
  "El cuerpo es un territorio político.|Pedro Lemebel"
  "Tener miedo es un derecho, lo que no es un derecho es dejar que el miedo te paralice.|Raúl Zurita"
  "La poesía es el último refugio de la dignidad humana.|Raúl Zurita"
  "El arte es la única forma de soportar la realidad.|Raúl Zurita"
  "Un libro es un jardín que se lleva en el bolsillo.|Enrique Lihn"
  "La realidad es una invención del lenguaje.|Enrique Lihn"
  "Solo el que sabe que está perdido puede ser encontrado.|Enrique Lihn"
  "La infancia es el lugar donde uno se queda para siempre.|Jorge Edwards"
  "La literatura es una forma de desobediencia.|Jorge Edwards"
  "La historia es un cuento contado por los vencedores.|Jorge Edwards"
  "Nadie es dueño de la verdad, solo de su propia experiencia.|Pía Barros"
  "Las palabras son las únicas huellas que dejamos.|Pía Barros"
  "Escribir es una forma de resistencia.|Pía Barros"
  "El olvido es la muerte de la cultura.|Diamela Eltit"
  "La identidad es una construcción constante.|Diamela Eltit"
  "El silencio también es una forma de hablar.|Diamela Eltit"
)
