# Spanish - España

matecito_phrases+=(
  "Caminante, son tus huellas el camino y nada más.|Antonio Machado"
  "Caminante, no hay camino, se hace camino al andar.|Antonio Machado"
  "Hoy es siempre todavía.|Antonio Machado"
  "La verdad es lo que es, y sigue siendo verdad aunque se piense al revés.|Antonio Machado"
  "Entre el vivir y el soñar hay una tercera cosa: adivínala.|Antonio Machado"
  "El ojo que ves no es ojo porque tú lo veas; es ojo porque te ve.|Antonio Machado"
  "Yo voy soñando caminos de la tarde.|Antonio Machado"
  "Para dialogar, preguntad primero; después... escuchad.|Antonio Machado"
  "Es el mejor de los buenos quien sabe que en esta vida todo es cuestión de medida.|Antonio Machado"
  "Nunca perseguí la gloria, ni dejar en la memoria de los hombres mi canción.|Antonio Machado"
  "Despacito y buena letra.|Antonio Machado"
  "El que espera desespera.|Antonio Machado"
  "Se miente más de la cuenta por falta de fantasía.|Antonio Machado"
  "Vivir es caminar brevemente hacia la muerte.|Antonio Machado"
  "Lo que sabemos es una gota de agua; lo que ignoramos es el océano.|Antonio Machado"
  "La vida es sueño y los sueños, sueños son.|Pedro Calderón de la Barca"
  "¿Qué es la vida? Un frenesí. ¿Qué es la vida? Una ilusión, una sombra, una ficción.|Pedro Calderón de la Barca"
  "El mayor delito del hombre es haber nacido.|Pedro Calderón de la Barca"
  "Aun en sueños no se pierde el hacer bien.|Pedro Calderón de la Barca"
  "El hombre que vive de ilusiones sería el más feliz si las ilusiones no acabasen.|Pedro Calderón de la Barca"
  "En todas partes cuecen habas.|Miguel de Cervantes"
  "El que no arriesga no cruza la mar.|Miguel de Cervantes"
  "La pluma es lengua del alma.|Miguel de Cervantes"
  "Donde una puerta se cierra, otra se abre.|Miguel de Cervantes"
  "Ladrón que roba a ladrón tiene cien años de perdón.|Miguel de Cervantes"
  "No con quien naces sino con quien paces.|Miguel de Cervantes"
  "El que lee mucho y anda mucho, ve mucho y sabe mucho.|Miguel de Cervantes"
  "La experiencia es la madre de la ciencia.|Miguel de Cervantes"
  "Más vale buena esperanza que ruin posesión.|Miguel de Cervantes"
  "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.|Miguel de Cervantes"
  "Poderoso caballero es don Dinero.|Francisco de Quevedo"
  "La mayor locura que puede hacer un hombre en esta vida es dejarse morir.|Francisco de Quevedo"
  "Querer enmendar con palabras lo que se ha errado con obras es necedad.|Francisco de Quevedo"
  "El sabio puede cambiar de opinión. El necio, nunca.|Francisco de Quevedo"
  "Vivir es caminar hacia la muerte.|Francisco de Quevedo"
  "Retirado en la paz de estos desiertos, con pocos pero doctos libros juntos.|Francisco de Quevedo"
  "La vida empieza cada día.|Federico García Lorca"
  "Para ver la vida de color de rosa hay que ponerse gafas rosas.|Federico García Lorca"
  "La poesía no quiere adeptos, quiere amantes.|Federico García Lorca"
  "El amor que no muere, no es amor.|Federico García Lorca"
  "Hay almas que tienen... ¿cómo diré yo?... un remanso de poesía que les da paz y les ilumina el camino.|Federico García Lorca"
  "Verde que te quiero verde.|Federico García Lorca"
  "A las cinco de la tarde.|Federico García Lorca"
  "El duende no se repite, como no se repiten las formas del mar en la tormenta.|Federico García Lorca"
  "La música es el arte más directo, entra por el oído y va al corazón.|Federico García Lorca"
  "Soy un hombre que expresa sus emociones sin temor.|Federico García Lorca"
  "Yo quiero que el agua te lleve y el viento.|Federico García Lorca"
  "El teatro es la poesía que se levanta del libro y se hace humana.|Federico García Lorca"
  "Las ciudades tienen una personalidad propia que las define.|Federico García Lorca"
  "Pensar es el trabajo más difícil que existe.|Federico García Lorca"
  "La vida es breve, el arte largo.|Miguel de Unamuno"
  "El fin del hombre no es la felicidad sino la gloria.|Miguel de Unamuno"
  "La fe que no duda es una fe muerta.|Miguel de Unamuno"
  "El progreso consiste en renovarse.|Miguel de Unamuno"
  "La envidia es la religión de los mediocres.|Miguel de Unamuno"
  "Me duele España.|Miguel de Unamuno"
  "Venceréis pero no convenceréis.|Miguel de Unamuno"
  "La ciencia dice: sé. La sabiduría dice: sufre.|Miguel de Unamuno"
  "El que no piensa, no existe.|Miguel de Unamuno"
  "Solo el que ha sufrido sabe comprender.|Miguel de Unamuno"
  "Necesito que alguien me necesite.|Miguel de Unamuno"
  "El hombre se define por lo que busca, no por lo que encuentra.|Miguel de Unamuno"
  "Vivir es crearse.|Miguel de Unamuno"
  "La duda es el principio de la sabiduría.|Miguel de Unamuno"
  "Hay que saber sufrir y saber gozar.|Miguel de Unamuno"
  "La vida es tragedia para el que siente y comedia para el que piensa.|José Ortega y Gasset"
  "Yo soy yo y mi circunstancia, y si no la salvo a ella no me salvo yo.|José Ortega y Gasset"
  "El hombre no tiene naturaleza sino historia.|José Ortega y Gasset"
  "Vivir es resolver continuamente el problema de la vida.|José Ortega y Gasset"
  "El amor es ese súbito sentimiento de que otra persona existe.|José Ortega y Gasset"
  "Decir lo que uno piensa y pensar lo que uno dice.|José Ortega y Gasset"
  "La claridad es la cortesía del filósofo.|José Ortega y Gasset"
  "La vida es disparada hacia adelante y solo puede comprenderse mirando hacia atrás.|José Ortega y Gasset"
  "El intelectual es el que prefiere deberle algo a la verdad antes que a la mentira.|José Ortega y Gasset"
  "Dime a qué prestas atención y te diré quién eres.|José Ortega y Gasset"
  "La soledad es el mayor lujo de la modernidad.|Camilo José Cela"
  "La palabra exacta es la que no se puede cambiar.|Camilo José Cela"
  "El arte es el refugio de la libertad.|Camilo José Cela"
  "La literatura española es una de las más ricas del mundo.|Camilo José Cela"
  "Escribir es pensar con la mano.|Camilo José Cela"
  "La novela es el género literario más humano.|Camilo José Cela"
  "La vida no es un ensayo general.|Camilo José Cela"
  "El lenguaje es el vestido del pensamiento.|Camilo José Cela"
  "La libertad de expresión es la base de toda cultura.|Camilo José Cela"
  "Cada palabra tiene su peso exacto.|Camilo José Cela"
  "Lo que sabemos es una gota, lo que ignoramos es un océano.|Baltasar Gracián"
  "Más valen quintaesencias que fárragos.|Baltasar Gracián"
  "El buen gusto suple el talento.|Baltasar Gracián"
  "Saber y saberlo demostrar es saber dos veces.|Baltasar Gracián"
  "La verdad siempre llega tarde, y llega cojeando.|Baltasar Gracián"
  "No hay mayor desdicha que la de un hombre que no conoce la fortuna.|Baltasar Gracián"
  "La perfección no consiste en hacer más cosas, sino en hacer bien las necesarias.|Baltasar Gracián"
  "El secreto para envejecer bien es no dejar de aprender.|Baltasar Gracián"
  "Es señal de buen gusto no gustar de todo.|Baltasar Gracián"
  "El hombre prudente hace de las necesidades virtudes.|Baltasar Gracián"
)
