# Spanish - México

matecito_phrases+=(
  "La soledad es el gran maestro del espíritu.|Octavio Paz"
  "La libertad no es una filosofía y ni siquiera es una idea: es un movimiento de la conciencia.|Octavio Paz"
  "La poesía es el antídoto de la tecnología.|Octavio Paz"
  "El amor es un estado de gracia.|Octavio Paz"
  "La modernidad es una forma del tiempo: la creencia en que el presente no se repite.|Octavio Paz"
  "Amar es combatir, es abrir puertas, dejar de ser fantasma con un número a perpetua cadena condenado.|Octavio Paz"
  "La palabra es el hombre mismo.|Octavio Paz"
  "La historia tiene la estructura de una metáfora.|Octavio Paz"
  "El otro no es el infierno: es lo que nos completa.|Octavio Paz"
  "La tradición no es la herencia sino la elección de la herencia.|Octavio Paz"
  "No me preguntes lo que el tiempo me ha enseñado — pregúntame lo que he aprendido del amor.|Octavio Paz"
  "La soledad es el fondo último de la condición humana.|Octavio Paz"
  "El presente es perpetuo.|Octavio Paz"
  "El lenguaje es la casa del ser.|Octavio Paz"
  "La crítica es el aprendizaje de la lectura.|Octavio Paz"
  "El hombre, ser de palabras.|Octavio Paz"
  "No hay más realidad que la que percibimos.|Octavio Paz"
  "La vida es un tejido de instantes.|Octavio Paz"
  "La democracia es el sistema político de la libertad.|Octavio Paz"
  "El amor es la condición humana por excelencia.|Octavio Paz"
  "Vivo sin vivir en mí y tan alta vida espero que muero porque no muero.|Sor Juana Inés de la Cruz"
  "Hombres necios que acusáis a la mujer sin razón, sin ver que sois la ocasión de lo mismo que culpáis.|Sor Juana Inés de la Cruz"
  "¿Qué más quisiera yo que saber más para merecer más?|Sor Juana Inés de la Cruz"
  "Yo no estudio para saber más, sino para ignorar menos.|Sor Juana Inés de la Cruz"
  "La ignorancia es el principio de todo mal.|Sor Juana Inés de la Cruz"
  "En perseguirme, mundo, ¿qué interesas?|Sor Juana Inés de la Cruz"
  "El saber tiene sus penas como la ignorancia sus ventajas.|Sor Juana Inés de la Cruz"
  "No hay sabiduría sin reflexión.|Sor Juana Inés de la Cruz"
  "El entendimiento que se cultiva nunca envejece.|Sor Juana Inés de la Cruz"
  "La curiosidad es la madre de todas las ciencias.|Sor Juana Inés de la Cruz"
  "Pinté la realidad tal y como yo la veía, no como otros querían que la viera.|Frida Kahlo"
  "Pies para qué los quiero, si tengo alas para volar.|Frida Kahlo"
  "Al final del día, podemos aguantar mucho más de lo que creemos posible.|Frida Kahlo"
  "Nada vale más que la risa. Es la fuerza reír y abandonarse, ser ligero.|Frida Kahlo"
  "Soy mi propio muso, el sujeto que mejor conozco y el que quiero conocer mejor.|Frida Kahlo"
  "La realidad más poderosa es el amor.|Frida Kahlo"
  "Espero que la partida sea feliz y espero no volver jamás.|Frida Kahlo"
  "Me pintó a mí misma porque soy a quien mejor conozco.|Frida Kahlo"
  "La vida callada, dadora de mundos.|Frida Kahlo"
  "Árbol de la esperanza, mantente firme.|Frida Kahlo"
  "La vida es una lucha constante.|Carlos Fuentes"
  "México es un país que vive entre el pasado y el futuro sin encontrar su presente.|Carlos Fuentes"
  "La imaginación es la única arma en la guerra contra la realidad.|Carlos Fuentes"
  "Escribir es negarse a morir.|Carlos Fuentes"
  "La novela es el espejo que camina a lo largo de un camino real.|Carlos Fuentes"
  "La identidad no se hereda, se construye.|Carlos Fuentes"
  "Un país que no lee no puede pensar.|Carlos Fuentes"
  "La cultura es la memoria de un pueblo.|Carlos Fuentes"
  "El pasado de México no ha muerto, vive en el presente.|Carlos Fuentes"
  "La literatura es el espacio donde todo es posible.|Carlos Fuentes"
  "México lindo y querido.|José Alfredo Jiménez"
  "La vida no vale nada si no es para entregar la vida por los demás.|Emiliano Zapata"
  "Es mejor morir de pie que vivir de rodillas.|Emiliano Zapata"
  "La tierra es de quien la trabaja.|Emiliano Zapata"
  "El pueblo que trabaja debe poseer los medios de trabajo.|Emiliano Zapata"
  "No dejes para mañana lo que puedes hacer hoy.|Benito Juárez"
  "El respeto al derecho ajeno es la paz.|Benito Juárez"
  "Entre los individuos, como entre las naciones, el respeto al derecho ajeno es la paz.|Benito Juárez"
  "La democracia es el destino de la humanidad; la libertad su indestructible arma.|Benito Juárez"
  "Nada hay más precioso que la libertad y la justicia.|Benito Juárez"
  "Que el pueblo y el gobierno respeten los derechos de todos.|Benito Juárez"
  "La ley es la expresión de la voluntad general.|Benito Juárez"
  "No soy enemigo de los ricos, pero más amigo de los pobres.|Benito Juárez"
  "La patria es primero.|Benito Juárez"
  "Sin libertad no hay patria.|Benito Juárez"
  "Escribir es una forma de terapia.|Juan Rulfo"
  "Vine a Comala porque me dijeron que acá vivía mi padre.|Juan Rulfo"
  "El olvido en que nos tuvo, mi hijo, cóbraselo caro.|Juan Rulfo"
  "Hay muertos que hacen mucho ruido al morir.|Juan Rulfo"
  "La vida no es muy seria en sus cosas.|Juan Rulfo"
  "Puedo vencer el tiempo si lo utilizo bien.|Juan Rulfo"
  "El pasado siempre pesa más que el futuro.|Juan Rulfo"
  "La soledad es la única compañía que no abandona.|Juan Rulfo"
  "Los muertos pesan más que los vivos.|Juan Rulfo"
  "Cada uno vive de su propia mentira.|Juan Rulfo"
  "El lenguaje es el instrumento del pensamiento.|Alfonso Reyes"
  "La cultura es la interpretación del mundo por el hombre.|Alfonso Reyes"
  "La crítica es el arte de saber leer.|Alfonso Reyes"
  "La literatura mexicana tiene raíces profundas.|Alfonso Reyes"
  "El humanismo es la conciencia de la humanidad.|Alfonso Reyes"
  "La educación es el camino de la libertad.|Alfonso Reyes"
  "No puede haber cultura sin crítica.|Alfonso Reyes"
  "El arte es la más alta expresión de la libertad humana.|Alfonso Reyes"
  "La poesía es conocimiento, salvación, poder, abandono.|Alfonso Reyes"
  "El pensamiento libre es la base de toda civilización.|Alfonso Reyes"
  "El tiempo es el maestro más sabio.|Elena Poniatowska"
  "La mujer mexicana es la columna vertebral de la familia y la sociedad.|Elena Poniatowska"
  "La literatura es un acto de resistencia.|Elena Poniatowska"
  "Escribir es una forma de sobrevivir.|Elena Poniatowska"
  "La memoria es la única forma de justicia que tenemos.|Elena Poniatowska"
  "El periodismo es la primera versión de la historia.|Elena Poniatowska"
  "Las mujeres tenemos que contarnos las unas a las otras.|Elena Poniatowska"
  "México es un país de grandes contrastes.|Elena Poniatowska"
  "La dignidad no se negocia.|Elena Poniatowska"
  "La lucha por la justicia no termina nunca.|Elena Poniatowska"
  "No se puede entender México sin entender su literatura.|Rosario Castellanos"
  "La mujer tiene que dejar de ser el ángel del hogar para convertirse en persona.|Rosario Castellanos"
  "La única manera de ser libre es asumir la responsabilidad de serlo.|Rosario Castellanos"
  "La literatura es la mejor manera de entender la condición humana.|Rosario Castellanos"
  "El amor no basta, hace falta la comprensión.|Rosario Castellanos"
  "La igualdad entre hombres y mujeres es una cuestión de justicia.|Rosario Castellanos"
  "El conocimiento es la única libertad verdadera.|Rosario Castellanos"
  "La cultura es la única patria que no se puede perder.|Rosario Castellanos"
)
