# Spanish - Uruguay

matecito_phrases+=(
  "Cuando creíamos que teníamos todas las respuestas, de pronto, nos cambiaron todas las preguntas.|Mario Benedetti"
  "Cinco minutos bastan para soñar toda una vida, así de relativo es el tiempo.|Mario Benedetti"
  "No vayas a creer lo que te cuentan del mundo, ya te dije que el mundo es incontable.|Mario Benedetti"
  "La perfección es una pulida colección de errores.|Mario Benedetti"
  "Después de todo la muerte es solo un síntoma de que hubo vida.|Mario Benedetti"
  "Mucha gente pequeña, en lugares pequeños, haciendo cosas pequeñas, puede cambiar el mundo.|Eduardo Galeano"
  "Al fin y al cabo, somos lo que hacemos para cambiar lo que somos.|Eduardo Galeano"
  "La utopía está en el horizonte. Camino dos pasos, ella se aleja dos pasos y el horizonte se corre diez pasos más allá.|Eduardo Galeano"
  "Estamos hechos de historias.|Eduardo Galeano"
  "Libres son quienes crean, no quienes copian; y libres son quienes piensan, no quienes obedecen.|Eduardo Galeano"
  "Hay un mundo para cada uno, y cada uno está en su mundo.|Ida Vitale"
  "La palabra es una trampa si no se la cuida.|Ida Vitale"
  "Leer es una forma de felicidad, pero también de resistencia.|Ida Vitale"
  "El olvido es una forma de libertad.|Ida Vitale"
  "La memoria es un país donde siempre somos extranjeros.|Cristina Peri Rossi"
  "Escribir es una manera de hablar solo sin que parezca una locura.|Cristina Peri Rossi"
  "El amor es una droga, y como toda droga, tiene sus efectos secundarios.|Cristina Peri Rossi"
  "La vida es una aventura que se cuenta mientras se vive.|Cristina Peri Rossi"
  "La realidad es un sueño que se vuelve pesadilla si no se lo sueña bien.|Juan Carlos Onetti"
  "Se dice que hay que sufrir para escribir, pero yo creo que hay que vivir para contar.|Juan Carlos Onetti"
  "El lenguaje es la única patria que tenemos.|Juan Carlos Onetti"
  "Nada es tan serio como parece cuando uno se ríe de sí mismo.|Juan Carlos Onetti"
  "El pensamiento es una forma de acción.|José Enrique Rodó"
  "Reformarse es vivir.|José Enrique Rodó"
  "Cada uno de nosotros es, sucesivamente, no uno, sino muchos.|José Enrique Rodó"
  "La juventud es la sonrisa del porvenir.|José Enrique Rodó"
  "La vida es un relámpago entre dos oscuridades.|Idea Vilariño"
  "No te vayas, no me dejes, que el mundo es un lugar oscuro sin tu luz.|Idea Vilariño"
  "El amor es un incendio que se apaga con el tiempo, pero las cenizas quedan.|Idea Vilariño"
  "Escribir es una forma de limpiar el alma.|Idea Vilariño"
  "La libertad es el derecho de hacer lo que las leyes permiten.|José Gervasio Artigas"
  "Sean los orientales tan ilustrados como valientes.|José Gervasio Artigas"
  "Mi autoridad emana de vosotros y ella cesa ante vuestra presencia soberana.|José Gervasio Artigas"
  "Con la verdad no ofendo ni temo.|José Gervasio Artigas"
  "La sencillez es la forma más difícil de la belleza.|Delmira Agustini"
  "El alma es un jardín que hay que cultivar con amor.|Delmira Agustini"
  "El deseo es una llama que consume lo que toca.|Delmira Agustini"
  "La poesía es el lenguaje de los ángeles en la tierra.|Delmira Agustini"
  "La ignorancia es la madre de todos los males.|Juana de Ibarbourou"
  "La belleza es un regalo, pero la inteligencia es un tesoro.|Juana de Ibarbourou"
  "El tiempo vuela, pero nosotros somos los pilotos.|Juana de Ibarbourou"
  "La vida es un regalo que se abre cada mañana.|Juana de Ibarbourou"
  "El futuro no es lo que va a pasar, sino lo que vamos a hacer.|Jorge Majfud"
  "La cultura es el ejercicio crítico de la inteligencia.|Jorge Majfud"
  "La historia la escriben los que sobreviven para contarla.|Jorge Majfud"
  "La verdadera libertad empieza en la educación.|Jorge Majfud"
  "El éxito es un viaje, no un destino.|Felisberto Hernández"
  "La música es el silencio que habla.|Felisberto Hernández"
  "Los recuerdos son como fantasmas que nos visitan de noche.|Felisberto Hernández"
  "La imaginación es la llave de todas las puertas cerradas.|Felisberto Hernández"
)
