# Portuguese - Brazil

matecito_phrases+=(
  "A esperança tem duas filhas lindas: a indignação e a coragem.|Paulo Coelho"
  "Quando você quer alguma coisa, todo o Universo conspira para que você realize o seu desejo.|Paulo Coelho"
  "Não existe o tempo perdido, existe o tempo que foi vivido.|Paulo Coelho"
  "O amor nunca é uma derrota; é o que nos torna fortes.|Paulo Coelho"
  "Não adie a vida que você poderia estar vivendo.|Paulo Coelho"
  "Feliz aquele que transfere o que sabe e aprende o que ensina.|Paulo Coelho"
  "Uma vida sem causa é uma vida sem efeito.|Paulo Coelho"
  "Os sonhos são a linguagem de Deus.|Paulo Coelho"
  "O segredo da vida é cair sete vezes e levantar oito.|Paulo Coelho"
  "Quando cada dia é igual ao anterior, é porque as pessoas deixaram de perceber as coisas boas que aparecem em suas vidas.|Paulo Coelho"
  "A coragem é o maior dom de Deus.|Paulo Coelho"
  "Deus não joga dados.|Paulo Coelho"
  "Todo poder emana do povo.|Getúlio Vargas"
  "O Brasil não é para principiantes.|Tom Jobim"
  "A música brasileira é a mais bela do mundo.|Tom Jobim"
  "A vida é a arte do encontro, embora haja tanto desencontro pela vida.|Vinícius de Moraes"
  "Amor é fogo que arde sem se ver, é ferida que dói e não se sente.|Vinícius de Moraes"
  "A vida não para.|Cazuza"
  "O tempo não para.|Cazuza"
  "Brasil, mostra a tua cara.|Cazuza"
  "Ser ou não ser, eis a questão.|Machado de Assis"
  "Não me perguntes o que é a vida; ela mesma não sabe.|Machado de Assis"
  "A vaidade é a maior de todas as vaidades.|Machado de Assis"
  "O amor é um estado de graça; a paixão, um estado de guerra.|Machado de Assis"
  "A melhor definição do amor é esta: amor é o desejo de dar.|Machado de Assis"
  "A vida tem muitas maneiras de ser vivida, não a desperdice.|Machado de Assis"
  "Cada geração tem seus problemas, cada época seus valores.|Machado de Assis"
  "Viver é lutar. A vida é o combate dos que querem vencer.|Machado de Assis"
  "O mundo é dos que acordam cedo.|Machado de Assis"
  "A saudade é a presença de uma ausência.|Machado de Assis"
  "Ninguém é perfeito sozinho, mas juntos podemos ser melhores.|Clarice Lispector"
  "Escrever é uma maldição que salva.|Clarice Lispector"
  "Sou feita de retalhos, pedaços coloridos de cada vida que passa pela minha.|Clarice Lispector"
  "Eu não sou inteligente. Sou apenas apaixonada, o que é bem diferente.|Clarice Lispector"
  "A maior aventura que se pode ter é a própria vida.|Clarice Lispector"
  "Nunca vi o amor ser fácil para alguém.|Clarice Lispector"
  "Felicidade? Nunca fui uma pessoa feliz; tenho euforia e curiosidade.|Clarice Lispector"
  "O que eu sei tem a forma do que não sei.|Clarice Lispector"
  "Eu sou o meu próprio silêncio.|Clarice Lispector"
  "Viver não é preciso, o que é preciso é criar.|Clarice Lispector"
  "A vida não para de surpreender quem sabe viver.|Clarice Lispector"
  "Sou o que quis ser porque me tornei o que sou.|Clarice Lispector"
  "O homem que nasce com uma vocação, e não a exerce, é um mutilado.|Jorge Amado"
  "A vida é uma coisa muito importante para ser deixada ao acaso.|Jorge Amado"
  "O povo brasileiro é o mais criativo do mundo.|Jorge Amado"
  "Na Bahia, tudo vira festa.|Jorge Amado"
  "A vida tem gosto de mangaba.|Jorge Amado"
  "O Brasil é um país de contrastes que se completam.|Jorge Amado"
  "A literatura é a melhor forma de conhecer um povo.|Jorge Amado"
  "A amizade é o único cimento que une o mundo.|Jorge Amado"
  "O amor é a força que move o mundo.|Jorge Amado"
  "A esperança é a última que morre.|Provérbio brasileiro"
  "Cada macaco no seu galho.|Provérbio brasileiro"
  "Água mole em pedra dura, tanto bate até que fura.|Provérbio brasileiro"
  "Deus escreve certo por linhas tortas.|Provérbio brasileiro"
  "Quem não arrisca, não petisca.|Provérbio brasileiro"
  "Não deixe para amanhã o que você pode fazer hoje.|Provérbio brasileiro"
  "A pressa é inimiga da perfeição.|Provérbio brasileiro"
  "A educação é a arma mais poderosa que você pode usar para mudar o mundo.|Paulo Freire"
  "Ninguém educa ninguém, ninguém educa a si mesmo, os homens se educam entre si, mediatizados pelo mundo.|Paulo Freire"
  "A leitura do mundo precede a leitura da palavra.|Paulo Freire"
  "Ensinar não é transferir conhecimento, mas criar as possibilidades para a sua própria produção ou construção.|Paulo Freire"
  "O homem é o único ser capaz de transformar o mundo.|Paulo Freire"
  "Não há saber mais, nem saber menos. Há saberes diferentes.|Paulo Freire"
  "A curiosidade é a base do aprendizado.|Paulo Freire"
  "A liberdade não é um presente que se dá, é uma conquista que se faz.|Paulo Freire"
  "Quem caminha sozinho pode até chegar mais rápido, mas aquele que vai acompanhado com certeza vai mais longe.|Paulo Freire"
  "A esperança é necessária, mas não suficiente.|Paulo Freire"
  "O amor é um ato de coragem.|Paulo Freire"
  "A humildade é a virtude de quem conhece suas limitações.|Paulo Freire"
  "Ter fé na vida e no amor é fundamental.|Paulo Freire"
  "A transformação do mundo implica dialeticamente a transformação dos homens.|Paulo Freire"
  "Não existe docência sem discência.|Paulo Freire"
  "O samba é a alma do Brasil.|Noel Rosa"
  "Quem não tem colinho, tem saudade.|Noel Rosa"
  "Com que roupa eu vou?|Noel Rosa"
  "A saudade é a mais bela das palavras.|Fernando Pessoa"
  "A vida é curta, a arte é longa.|Hipócrates (em português)"
  "Não há rosas sem espinhos.|Provérbio brasileiro"
  "Todo brasileiro carrega dentro de si a saudade.|Darcy Ribeiro"
  "O Brasil é um país do futuro, e sempre será.|Stefan Zweig"
  "A criatividade é a inteligência se divertindo.|Millôr Fernandes"
  "O ridículo mata, mas mata devagar.|Millôr Fernandes"
  "A ironia é a forma mais elegante da inteligência.|Millôr Fernandes"
  "O Brasil é o país do carnaval e do choro.|Pixinguinha"
  "Nenhum vento é favorável para quem não sabe para onde vai.|Sêneca (em português)"
  "A esperança sustenta a vida.|Provérbio brasileiro"
  "Minha terra tem palmeiras, onde canta o sabiá.|Gonçalves Dias"
  "Liberdade, liberdade, abre as asas sobre nós.|Joaquim Osório Duque-Estrada"
  "Independência ou morte!|Dom Pedro I"
  "O Brasil nasceu da mistura e da esperança.|Darcy Ribeiro"
  "A identidade brasileira é uma construção permanente.|Darcy Ribeiro"
  "A cultura brasileira é uma das mais ricas do mundo.|Darcy Ribeiro"
  "O povo brasileiro é alegre por necessidade.|Nelson Rodrigues"
  "A vida é um sonho de que às vezes se acorda.|Nelson Rodrigues"
  "No Brasil, tudo acaba em pizza.|Nelson Rodrigues"
  "O futebol é o ópio do povo brasileiro.|Nelson Rodrigues"
  "A morte é a única certeza que temos.|Nelson Rodrigues"
  "O amor é sempre a primeira vez.|Nelson Rodrigues"
)
