# Portuguese - Portugal

matecito_phrases+=(
  "Não sou nada. Nunca serei nada. Não posso querer ser nada. À parte isso, tenho em mim todos os sonhos do mundo.|Fernando Pessoa"
  "Navegar é preciso, viver não é preciso.|Fernando Pessoa"
  "Viajar! Perder países! Ser outro constantemente!|Fernando Pessoa"
  "O valor das coisas não está no tempo que elas duram, mas na intensidade com que acontecem.|Fernando Pessoa"
  "Não sou pessimista. Sou um optimista bem informado.|Fernando Pessoa"
  "A minha pátria é a língua portuguesa.|Fernando Pessoa"
  "Tudo vale a pena quando a alma não é pequena.|Fernando Pessoa"
  "Sou o intervalo entre o meu desejo e aquilo que a vida fez de mim.|Fernando Pessoa"
  "Não sou ninguém. Sou um intervalo entre o que desejo e o que a vida fez de mim.|Fernando Pessoa"
  "O amor é a consciência de duas solidões.|Fernando Pessoa"
  "Acontece que eu sou do tamanho do que vejo e não do tamanho da minha altura.|Fernando Pessoa"
  "Não há problema que não passe.|Fernando Pessoa"
  "Há um tempo em que é preciso abandonar as roupas usadas.|Fernando Pessoa"
  "O que nós vemos das coisas são as coisas.|Fernando Pessoa"
  "Toda a teoria é cinzenta, meu caro, verde é a árvore dourada da vida.|Fernando Pessoa"
  "O sono é a única libertação que a vida nos dá ainda em vida.|Fernando Pessoa"
  "Ser grande é ser mal interpretado.|Fernando Pessoa"
  "A poesia é a forma mais pura de pensar.|Fernando Pessoa"
  "A única forma de viajar é sentir.|Fernando Pessoa"
  "O real é o que não passa.|Fernando Pessoa"
  "Que o vento que passa diga ao mar que não me esqueci de ti.|Luís de Camões"
  "Por mares nunca dantes navegados.|Luís de Camões"
  "Mudam-se os tempos, mudam-se as vontades.|Luís de Camões"
  "Amor é fogo que arde sem se ver; é ferida que dói e não se sente.|Luís de Camões"
  "A força não vence o direito.|Luís de Camões"
  "Que cousas haverá que o mundo encerre, que mereçam que alguém por elas erre?|Luís de Camões"
  "Os bons vi sempre passar no mundo grandes tormentos.|Luís de Camões"
  "Um castelo que não tem fundação não tem valor.|Luís de Camões"
  "A saudade é o amor que ficou.|Luís de Camões"
  "Ó gloriosa lusitana gente!|Luís de Camões"
  "Nenhum de nós sabe o que quer, nenhum de nós sabe o que pensa, nenhum de nós sabe o que sente.|José Saramago"
  "A consciência é o principal espaço da liberdade humana.|José Saramago"
  "Cada um de nós é o que viu, o que leu, o que esqueceu, o que quis e o que perdeu.|José Saramago"
  "Não me resigno. A resignação é a virtude mais covarde.|José Saramago"
  "Se podes olhar, vê. Se podes ver, repara.|José Saramago"
  "O tempo não pára, nós é que paramos.|José Saramago"
  "A leitura é uma espécie de pensamento em voz alta.|José Saramago"
  "Somos feitos da memória dos outros.|José Saramago"
  "Dentro de cada um de nós há um desconhecido a quem chamamos eu.|José Saramago"
  "A morte é apenas o fim da vida, não o fim da existência.|José Saramago"
  "O homem é o que come e o que lê.|José Saramago"
  "As palavras são apenas pedras postas a atravessar a corrente de um rio.|José Saramago"
  "Todo o amor é a primeira vez.|José Saramago"
  "A vida não é o que vivemos, é o que recordamos e como recordamos.|José Saramago"
  "A beleza salvará o mundo, se o mundo deixar.|José Saramago"
  "A saudade é uma lembrança que dói.|Provérbio português"
  "Quem não arrisca, não petisca.|Provérbio português"
  "Devagar se vai ao longe.|Provérbio português"
  "Água mole em pedra dura, tanto bate até que fura.|Provérbio português"
  "A esperança é o último bem que se perde.|Provérbio português"
  "O mar não está para peixe.|Provérbio português"
  "Grão a grão enche a galinha o papo.|Provérbio português"
  "A saudade é uma doença portuguesa.|António Lobo Antunes"
  "Portugal é um sonho antigo.|António Lobo Antunes"
  "A escrita é a melhor forma de conhecer a si mesmo.|António Lobo Antunes"
  "A memória é o que nos faz ser quem somos.|António Lobo Antunes"
  "Portugal tem uma história que pesa sobre o presente.|António Lobo Antunes"
  "Escrever é uma forma de sobreviver.|António Lobo Antunes"
  "A literatura portuguesa é a mais melancólica do mundo.|António Lobo Antunes"
  "O fado é a música da saudade.|António Lobo Antunes"
  "A vida é uma dor que vale a pena.|António Lobo Antunes"
  "Portugal está sempre a começar.|António Lobo Antunes"
  "A saudade é a presença de uma ausência.|Agustina Bessa-Luís"
  "Portugal é um país de poetas e navegadores.|Agustina Bessa-Luís"
  "A mulher portuguesa tem a força do fado na alma.|Agustina Bessa-Luís"
  "A tradição é o presente do passado.|Agustina Bessa-Luís"
  "Escrever é resistir ao esquecimento.|Agustina Bessa-Luís"
  "A vida é uma metáfora que não sabemos ler.|Agustina Bessa-Luís"
  "O amor verdadeiro nunca envelhece.|Agustina Bessa-Luís"
  "A beleza está no olhar de quem vê.|Agustina Bessa-Luís"
  "Portugal tem o melhor pôr do sol do mundo.|Agustina Bessa-Luís"
  "A língua portuguesa é um tesouro.|Agustina Bessa-Luís"
  "Deus quer, o homem sonha, a obra nasce.|Fernando Pessoa"
  "E o mar foi e a terra foi e o ar foi.|Fernando Pessoa"
  "Lisboa, antiga e triste, como eu.|Fernando Pessoa"
  "O Tejo é mais belo que o rio que corre pela minha aldeia.|Fernando Pessoa"
  "Não sou eu que descrevo, é o universo que se descreve em mim.|Fernando Pessoa"
  "Portugal é uma sensação.|Fernando Pessoa"
  "Há metáforas mais consoladoras que a verdade.|Fernando Pessoa"
  "A vida é uma viagem de ida e sem volta.|Fernando Pessoa"
  "O sonho comanda a vida.|António Gedeão"
  "Pedra filosofal: o povo que há-de vir.|António Gedeão"
  "A ciência tem o futuro na mão.|António Gedeão"
  "O homem que não lê não é melhor do que o que não sabe ler.|Eça de Queirós"
  "A ironia é o pudor do sentimento.|Eça de Queirós"
  "O melhor é inimigo do bom.|Eça de Queirós"
  "A civilização é a humanização do homem em sociedade.|Eça de Queirós"
  "Portugal é um país mal governado, mas bem vivido.|Eça de Queirós"
  "A corrupção começa onde termina a educação.|Eça de Queirós"
  "O amor não tem lógica, mas tem coração.|Eça de Queirós"
  "Não há nada mais triste do que um homem que perdeu a esperança.|Eça de Queirós"
  "A glória literária é a sombra da glória real.|Eça de Queirós"
  "Viver em Portugal é um estado de alma.|Eça de Queirós"
)
