# Italian - Italy

matecito_phrases+=(
  "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.|Dante Alighieri"
  "L'amor che move il sole e l'altre stelle.|Dante Alighieri"
  "Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza.|Dante Alighieri"
  "Lasciate ogne speranza, voi ch'intrate.|Dante Alighieri"
  "La bocca mi baciò tutto tremante.|Dante Alighieri"
  "Nessun maggior dolore che ricordarsi del tempo felice nella miseria.|Dante Alighieri"
  "E quindi uscimmo a riveder le stelle.|Dante Alighieri"
  "L'amore e 'l cor gentil sono una cosa.|Dante Alighieri"
  "Non ragioniam di lor, ma guarda e passa.|Dante Alighieri"
  "Considerate la vostra semenza: fatti non foste a viver come bruti.|Dante Alighieri"
  "Il poeta nasce, non si fa.|Orazio"
  "La vita è breve, l'arte è lunga.|Ippocrate (in italiano)"
  "Chi legge molto sa molto, chi vive molto capisce molto.|Leonardo da Vinci"
  "L'esperienza è la madre di tutta la scienza.|Leonardo da Vinci"
  "Quello che ostacola la tua strada, diventa la tua strada.|Marco Aurelio (in italiano)"
  "La semplicità è la sofisticazione suprema.|Leonardo da Vinci"
  "L'acqua è il motore della natura.|Leonardo da Vinci"
  "Il ferro si arrugginisce per mancanza d'uso, l'acqua stagnante perde la sua purezza, e nel freddo si solidifica. Così l'ozio logora l'intelligenza.|Leonardo da Vinci"
  "Dove la libertà è carente, la felicità è proibita.|Leonardo da Vinci"
  "Chi poco conosce, poco ama.|Leonardo da Vinci"
  "Non girare il mondo in cerca di meraviglie, esse stanno nella tua anima.|Agostino di Ippona"
  "Il nostro cuore è inquieto finché non riposa in te.|Sant'Agostino"
  "Ama e fa' ciò che vuoi.|Sant'Agostino"
  "La misura dell'amore è amare senza misura.|Sant'Agostino"
  "Hai fatto per te stesso il nostro cuore, o Signore, e non troverà pace finché non si riposi in te.|Sant'Agostino"
  "Il tempo è un grande maestro, ma purtroppo uccide tutti i suoi allievi.|Hector Berlioz (in italiano)"
  "Il bello è eterno.|Benedetto Croce"
  "L'arte è ciò che ci distingue dagli animali.|Benedetto Croce"
  "La filosofia è la scienza dello spirito.|Benedetto Croce"
  "La storia è sempre storia contemporanea.|Benedetto Croce"
  "La libertà è la condizione dello spirito.|Benedetto Croce"
  "Il pensiero è la forma più alta di attività umana.|Benedetto Croce"
  "La critica letteraria è un'arte.|Benedetto Croce"
  "L'intuizione è la prima forma della conoscenza.|Benedetto Croce"
  "La morale non si insegna, si vive.|Benedetto Croce"
  "La cultura è la forma più alta di patriottismo.|Benedetto Croce"
  "Se non ora, quando?|Primo Levi"
  "Chi non conosce il passato è condannato a ripeterlo.|Primo Levi"
  "È accaduto, quindi può accadere di nuovo.|Primo Levi"
  "La memoria è il fondamento dell'identità.|Primo Levi"
  "Vivere è resistere.|Primo Levi"
  "La dignità è l'unica cosa che non si può togliere a un uomo.|Primo Levi"
  "Il lavoro rende liberi — ma non in quel senso.|Primo Levi"
  "Ricordare è un atto morale.|Primo Levi"
  "La testimonianza è un dovere.|Primo Levi"
  "L'indifferenza è il male del nostro tempo.|Primo Levi"
  "Il futuro ha un cuore antico.|Carlo Levi"
  "L'Italia è un paese di furbi e di santi.|Carlo Levi"
  "Il potere è sempre un male.|Carlo Levi"
  "La libertà non è stare sopra un albero.|Giorgio Gaber"
  "La libertà è partecipazione.|Giorgio Gaber"
  "L'intelligenza è la capacità di adattarsi al cambiamento.|Stephen Hawking (in italiano)"
  "Il dubbio è il principio della saggezza.|Aristotele (in italiano)"
  "La vita non vissuta non vale la pena di essere esaminata.|Socrate (in italiano)"
  "Conosci te stesso.|Socrate (in italiano)"
  "La virtù è la strada di mezzo.|Aristotele (in italiano)"
  "Il tutto è più della somma delle sue parti.|Aristotele (in italiano)"
  "La bellezza è negli occhi di chi guarda.|Proverbio italiano"
  "Chi dorme non piglia pesci.|Proverbio italiano"
  "Il tempo è denaro.|Proverbio italiano"
  "A caval donato non si guarda in bocca.|Proverbio italiano"
  "Tra il dire e il fare c'è di mezzo il mare.|Proverbio italiano"
  "Chi va piano va sano e va lontano.|Proverbio italiano"
  "Meglio tardi che mai.|Proverbio italiano"
  "L'abito non fa il monaco.|Proverbio italiano"
  "Non rimandare a domani quello che puoi fare oggi.|Proverbio italiano"
  "Il riso fa buon sangue.|Proverbio italiano"
  "La parola è d'argento, il silenzio è d'oro.|Proverbio italiano"
  "Tutto il mondo è paese.|Proverbio italiano"
  "Non c'è due senza tre.|Proverbio italiano"
  "Il lupo perde il pelo ma non il vizio.|Proverbio italiano"
  "L'uomo è la misura di tutte le cose.|Protagora (in italiano)"
  "Il coraggio è resistenza alla paura, non assenza di paura.|Mark Twain (in italiano)"
  "La musica è il linguaggio universale dell'umanità.|Henry Wadsworth Longfellow (in italiano)"
  "Ogni limite è un'opportunità.|Proverbio italiano"
  "Il presente è l'unico tempo che ci appartiene davvero.|Proverbio italiano"
  "L'amicizia è l'unica cosa al mondo la cui utilità è unanimemente riconosciuta.|Cicerone (in italiano)"
  "Dum spiro, spero. Finché respiro, spero.|Cicerone (in italiano)"
  "Il silenzio è d'oro.|Proverbio italiano"
  "Chi cerca trova.|Proverbio italiano"
  "Paese che vai, usanze che trovi.|Proverbio italiano"
  "Non si vive di solo pane.|Proverbio italiano"
  "La fortuna aiuta gli audaci.|Virgilio (in italiano)"
  "Omnia vincit amor. L'amore vince tutto.|Virgilio (in italiano)"
  "Il tempo guarisce tutte le ferite.|Proverbio italiano"
  "L'amore è cieco.|Proverbio italiano"
  "Errare è umano, perseverare è diabolico.|Proverbio italiano"
  "Meglio un giorno da leone che cent'anni da pecora.|Benito Mussolini"
  "L'Italia è una nazione di poeti, di artisti, di eroi, di santi, di pensatori, di scienziati, di navigatori, di trasmigratori.|Benito Mussolini"
  "Il fascismo è la più seria risposta al liberalismo.|Benito Mussolini"
  "L'arte di governare non consiste nel far felice la gente, ma nel non renderla infelice.|Niccolò Machiavelli"
  "È meglio essere amati o temuti? È molto più sicuro essere temuti che amati.|Niccolò Machiavelli"
  "I mezzi giustificano il fine.|Niccolò Machiavelli"
  "La fortuna è arbitra della metà delle nostre azioni.|Niccolò Machiavelli"
  "Un principe deve apparire clemente, fedele, umano, retto, religioso.|Niccolò Machiavelli"
  "La potenza e la gloria non si ottengono mai senza fatica.|Niccolò Machiavelli"
  "Chi vuole diventare principe deve usare sia la forza che l'astuzia.|Niccolò Machiavelli"
  "La guerra è l'unico modo per ottenere la vera pace.|Niccolò Machiavelli"
  "E pur si muove.|Galileo Galilei"
  "La natura è un libro scritto in linguaggio matematico.|Galileo Galilei"
  "Misura ciò che è misurabile, e rendi misurabile ciò che non lo è.|Galileo Galilei"
  "Il sole, con tutti quei pianeti che gli orbitano attorno, ancora riesce a far maturare i grappoli d'uva come se non avesse altro da fare.|Galileo Galilei"
  "La scienza è la figlia dell'esperienza.|Galileo Galilei"
  "Non si può insegnare nulla ad un uomo; lo si può solo aiutare a scoprire ciò che ha già dentro di sé.|Galileo Galilei"
)
