# English - United Kingdom

matecito_phrases+=(
  "To be, or not to be, that is the question.|William Shakespeare"
  "All the world's a stage, and all the men and women merely players.|William Shakespeare"
  "The fool doth think he is wise, but the wise man knows himself to be a fool.|William Shakespeare"
  "In a time of deceit telling the truth is a revolutionary act.|George Orwell"
  "Big Brother is Watching You.|George Orwell"
  "All animals are equal, but some animals are more equal than others.|George Orwell"
  "If you want a picture of the future, imagine a boot stamping on a human face—forever.|George Orwell"
  "A room of one's own.|Virginia Woolf"
  "No need to hurry. No need to sparkle. No need to be anybody but oneself.|Virginia Woolf"
  "I have nothing to offer but blood, toil, tears and sweat.|Winston Churchill"
  "Success consists of going from failure to failure without loss of enthusiasm.|Winston Churchill"
  "The best argument against democracy is a five-minute conversation with the average voter.|Winston Churchill"
  "We are all in the gutter, but some of us are looking at the stars.|Oscar Wilde"
  "Be yourself; everyone else is already taken.|Oscar Wilde"
  "I can resist everything except temptation.|Oscar Wilde"
  "Experience is simply the name we give our mistakes.|Oscar Wilde"
  "The only way to get rid of a temptation is to yield to it.|Oscar Wilde"
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.|Jane Austen"
  "I declare after all there is no enjoyment like reading!|Jane Austen"
  "There is no charm equal to tenderness of heart.|Jane Austen"
  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.|Jane Austen"
  "Not all those who wander are lost.|J.R.R. Tolkien"
  "Even the smallest person can change the course of the future.|J.R.R. Tolkien"
  "It is the unknown we fear when we look upon death and darkness, nothing more.|J.K. Rowling"
  "Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.|J.K. Rowling"
  "Life is what happens when you're busy making other plans.|John Lennon"
  "Imagination is the only weapon in the war against reality.|Lewis Carroll"
  "If you don't know where you are going, any road will get you there.|Lewis Carroll"
  "Curiouser and curiouser!|Lewis Carroll"
  "A man who dares to waste one hour of time has not discovered the value of life.|Charles Darwin"
  "It is not the strongest of the species that survives, nor the most intelligent; it is the one that is most adaptable to change.|Charles Darwin"
  "The mystery of the beginning of all things is insoluble by us.|Charles Darwin"
  "If I have seen further it is by standing on the shoulders of Giants.|Isaac Newton"
  "I can calculate the motion of heavenly bodies, but not the madness of people.|Isaac Newton"
  "Tact is the knack of making a point without making an enemy.|Isaac Newton"
  "It is a capital mistake to theorize before one has data.|Arthur Conan Doyle"
  "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.|Arthur Conan Doyle"
  "The more original a discovery, the more obvious it seems afterwards.|Arthur Conan Doyle"
  "Logic is the beginning of wisdom, not the end.|Leonard Nimoy"
  "Whatever is begun in anger ends in shame.|Benjamin Franklin"
  "There is no such thing as a free lunch.|Milton Friedman"
  "Power tends to corrupt, and absolute power corrupts absolutely.|Lord Acton"
  "The only thing necessary for the triumph of evil is for good men to do nothing.|Edmund Burke"
  "Reading is to the mind what exercise is to the body.|Joseph Addison"
  "The weak can never forgive. Forgiveness is the attribute of the strong.|Mahatma Gandhi"
  "The future depends on what you do today.|Mahatma Gandhi"
  "Where there is love there is life.|Mahatma Gandhi"
  "Life is a journey, not a destination.|Ralph Waldo Emerson"
  "The best way to predict the future is to create it.|Peter Drucker"
)
