# English - United Kingdom

matecito_phrases+=(
  "We are all in the gutter, but some of us are looking at the stars.|Oscar Wilde"
  "To live is the rarest thing in the world. Most people exist, that is all.|Oscar Wilde"
  "Be yourself; everyone else is already taken.|Oscar Wilde"
  "Always forgive your enemies; nothing annoys them so much.|Oscar Wilde"
  "I can resist everything except temptation.|Oscar Wilde"
  "The truth is rarely pure and never simple.|Oscar Wilde"
  "A cynic is a man who knows the price of everything and the value of nothing.|Oscar Wilde"
  "Every saint has a past, and every sinner has a future.|Oscar Wilde"
  "Experience is simply the name we give our mistakes.|Oscar Wilde"
  "To define is to limit.|Oscar Wilde"
  "The only way to get rid of a temptation is to yield to it.|Oscar Wilde"
  "I am not young enough to know everything.|Oscar Wilde"
  "It is what you read when you don't have to that determines what you will be when you can't help it.|Oscar Wilde"
  "With freedom, books, flowers, and the moon, who could not be happy?|Oscar Wilde"
  "Life is too important to be taken seriously.|Oscar Wilde"
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.|Jane Austen"
  "I declare after all there is no enjoyment like reading!|Jane Austen"
  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.|Jane Austen"
  "There is nothing I would not do for those who are really my friends.|Jane Austen"
  "A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.|Jane Austen"
  "Happiness in marriage is entirely a matter of chance.|Jane Austen"
  "I may have lost my heart, but not my self-control.|Jane Austen"
  "One cannot be always laughing at a man without now and then stumbling on something witty.|Jane Austen"
  "Angry people are not always wise.|Jane Austen"
  "Vanity and pride are different things, though the words are often used synonymously.|Jane Austen"
  "It is a far, far better thing that I do, than I have ever done.|Charles Dickens"
  "No one is useless in this world who lightens the burdens of another.|Charles Dickens"
  "We need never be ashamed of our tears.|Charles Dickens"
  "There are books of which the backs and covers are by far the best parts.|Charles Dickens"
  "The pain of parting is nothing to the joy of meeting again.|Charles Dickens"
  "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.|Charles Dickens"
  "Reflect upon your present blessings, of which every man has many.|Charles Dickens"
  "It is a pleasant thing to reflect upon, and furnish matter for amusing speculation.|Charles Dickens"
  "Family not only need to consist of merely those whom we share blood, but also for those whom we'd give blood.|Charles Dickens"
  "Electric communication will never be a substitute for the face of someone who with their soul encourages another person to be brave and true.|Charles Dickens"
  "Not all those who wander are lost.|J.R.R. Tolkien"
  "All we have to decide is what to do with the time that is given us.|J.R.R. Tolkien"
  "Even the smallest person can change the course of the future.|J.R.R. Tolkien"
  "I wish it need not have happened in my time.|J.R.R. Tolkien"
  "It's the job that's never started as takes longest to finish.|J.R.R. Tolkien"
  "Courage is found in unlikely places.|J.R.R. Tolkien"
  "There is some good in this world, and it's worth fighting for.|J.R.R. Tolkien"
  "The world is indeed full of peril and in it there are many dark places.|J.R.R. Tolkien"
  "Short cuts make long delays.|J.R.R. Tolkien"
  "If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.|J.R.R. Tolkien"
  "It does not do to dwell on dreams and forget to live.|J.K. Rowling"
  "It is our choices that show what we truly are, far more than our abilities.|J.K. Rowling"
  "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.|J.K. Rowling"
  "We are only as strong as we are united, as weak as we are divided.|J.K. Rowling"
  "Words are our most inexhaustible source of magic.|J.K. Rowling"
  "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.|J.K. Rowling"
  "To the well-organized mind, death is but the next great adventure.|J.K. Rowling"
  "I am what I am, an' I'm not ashamed.|J.K. Rowling"
  "When in doubt, go to the library.|J.K. Rowling"
  "Things we lose have a way of coming back to us in the end, if not always in the way we expect.|J.K. Rowling"
  "To be or not to be, that is the question.|William Shakespeare"
  "All the world's a stage, and all the men and women merely players.|William Shakespeare"
  "We know what we are, but know not what we may be.|William Shakespeare"
  "The lady doth protest too much, methinks.|William Shakespeare"
  "What's in a name? That which we call a rose by any other name would smell as sweet.|William Shakespeare"
  "This above all: to thine own self be true.|William Shakespeare"
  "All that glitters is not gold.|William Shakespeare"
  "The course of true love never did run smooth.|William Shakespeare"
  "Brevity is the soul of wit.|William Shakespeare"
  "We are such stuff as dreams are made on.|William Shakespeare"
  "It was a bright cold day in April, and the clocks were striking thirteen.|George Orwell"
  "All animals are equal, but some animals are more equal than others.|George Orwell"
  "In a time of deceit, telling the truth is a revolutionary act.|George Orwell"
  "Who controls the past controls the future. Who controls the present controls the past.|George Orwell"
  "If liberty means anything at all, it means the right to tell people what they do not want to hear.|George Orwell"
  "Doublethink means the power of holding two contradictory beliefs in one's mind simultaneously.|George Orwell"
  "The most effective way to destroy people is to deny and obliterate their own understanding of their history.|George Orwell"
  "Freedom is the freedom to say that two plus two make four.|George Orwell"
  "Big Brother is watching you.|George Orwell"
  "War is peace. Freedom is slavery. Ignorance is strength.|George Orwell"
  "Elementary, my dear Watson.|Arthur Conan Doyle"
  "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.|Arthur Conan Doyle"
  "The world is full of obvious things which nobody by any chance ever observes.|Arthur Conan Doyle"
  "It is a capital mistake to theorize before one has data.|Arthur Conan Doyle"
  "My mind rebels at stagnation.|Arthur Conan Doyle"
  "Education never ends, Watson. It is a series of lessons, with the greatest for the last.|Arthur Conan Doyle"
  "There is nothing more deceptive than an obvious fact.|Arthur Conan Doyle"
  "Once you eliminate the impossible, whatever remains, no matter how improbable, must be the truth.|Arthur Conan Doyle"
  "I never make exceptions. An exception disproves the rule.|Arthur Conan Doyle"
  "The game is afoot.|Arthur Conan Doyle"
  "It matters not how strait the gate, how charged with punishments the scroll.|William Ernest Henley"
  "I am the master of my fate, I am the captain of my soul.|William Ernest Henley"
  "In the fell clutch of circumstance I have not winced nor cried aloud.|William Ernest Henley"
  "Under the bludgeonings of chance my head is bloody, but unbowed.|William Ernest Henley"
  "Two roads diverged in a wood, and I took the one less traveled by.|Rudyard Kipling"
  "If you can meet with triumph and disaster and treat those two impostors just the same.|Rudyard Kipling"
  "Words are, of course, the most powerful drug used by mankind.|Rudyard Kipling"
  "We have forty million reasons for failure, but not a single excuse.|Rudyard Kipling"
  "If you can keep your head when all about you are losing theirs.|Rudyard Kipling"
  "A man's mind is wont to tell him more than seven watchmen sitting in a tower.|Rudyard Kipling"
)
