# English - United States

matecito_phrases+=(
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.|Ralph Waldo Emerson"
  "The only thing we have to fear is fear itself.|Franklin D. Roosevelt"
  "Success is not final, failure is not fatal: it is the courage to continue that counts.|Winston Churchill"
  "Do what you can, with what you have, where you are.|Theodore Roosevelt"
  "The future belongs to those who believe in the beauty of their dreams.|Eleanor Roosevelt"
  "In the end, it's not the years in your life that count. It's the life in your years.|Abraham Lincoln"
  "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.|Martin Luther King Jr."
  "If you tell the truth, you don't have to remember anything.|Mark Twain"
  "The man who does not read has no advantage over the man who cannot read.|Mark Twain"
  "The scariest moment is always just before you start.|Stephen King"
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.|Stephen King"
  "Write the truest sentence that you know.|Ernest Hemingway"
  "We are all broken, that's how the light gets in.|Ernest Hemingway"
  "That it will never come again is what makes life so sweet.|Emily Dickinson"
  "One day I will find the right words, and they will be simple.|Jack Kerouac"
  "There is no greater agony than bearing an untold story inside you.|Maya Angelou"
  "A bird doesn't sing because it has an answer, it sings because it has a song.|Maya Angelou"
  "Ask not what your country can do for you; ask what you can do for your country.|John F. Kennedy"
  "Nothing is certain except for death and taxes.|Benjamin Franklin"
  "Three can keep a secret, if two of them are dead.|Benjamin Franklin"
  "Well done is better than well said.|Benjamin Franklin"
  "Whatever you are, be a good one.|Abraham Lincoln"
  "No one can make you feel inferior without your consent.|Eleanor Roosevelt"
  "The only way to have a friend is to be one.|Ralph Waldo Emerson"
  "Imagination is everything. It is the preview of life's coming attractions.|Albert Einstein"
  "You don't write because you want to say something, you write because you have something to say.|F. Scott Fitzgerald"
  "The difference between the almost right word and the right word is the difference between the lightning bug and the lightning.|Mark Twain"
  "It is never too late to be what you might have been.|George Eliot"
  "Stay hungry, stay foolish.|Steve Jobs"
  "The people who are crazy enough to think they can change the world are the ones who do.|Steve Jobs"
  "Start writing, no matter what. The water does not flow until the faucet is turned on.|Louis L'Amour"
  "Freedom is never more than one generation away from extinction.|Ronald Reagan"
  "Information is the currency of democracy.|Thomas Jefferson"
  "I cannot live without books.|Thomas Jefferson"
  "The truest of all faces is the mask.|Walt Whitman"
  "I am large, I contain multitudes.|Walt Whitman"
  "Keep your face always toward the sunshine and shadows will fall behind you.|Walt Whitman"
  "The secret of getting ahead is getting started.|Mark Twain"
  "Logic will get you from A to B. Imagination will take you everywhere.|Albert Einstein"
  "Life is what happens when you're making other plans.|John Lennon"
  "Don't count the days, make the days count.|Muhammad Ali"
  "Truth is stranger than fiction.|Mark Twain"
  "A person who never made a mistake never tried anything new.|Albert Einstein"
  "Everything you've ever wanted is on the other side of fear.|George Addair"
  "Happiness is not something readymade. It comes from your own actions.|Dalai Lama"
  "Your time is limited, so don't waste it living someone else's life.|Steve Jobs"
  "Believe you can and you're halfway there.|Theodore Roosevelt"
  "Great thoughts speak only to the thoughtful mind, but great actions speak to all mankind.|Theodore Roosevelt"
  "The world is a book and those who do not travel read only one page.|St. Augustine"
  "It does not matter how slowly you go as long as you do not stop.|Confucius"
)
