# English - United States

matecito_phrases+=(
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.|Ralph Waldo Emerson"
  "The only thing we have to fear is fear itself.|Franklin D. Roosevelt"
  "Success is not final, failure is not fatal: it is the courage to continue that counts.|Winston Churchill"
  "Do what you can, with what you have, where you are.|Theodore Roosevelt"
  "The future belongs to those who believe in the beauty of their dreams.|Eleanor Roosevelt"
  "In the end, it's not the years in your life that count. It's the life in your years.|Abraham Lincoln"
  "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin but by the content of their character.|Martin Luther King Jr."
  "If you tell the truth, you don't have to remember anything.|Mark Twain"
  "The man who does not read has no advantage over the man who cannot read.|Mark Twain"
  "The scariest moment is always just before you start.|Stephen King"
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.|Stephen King"
  "Write the truest sentence that you know.|Ernest Hemingway"
  "We are all broken, that's how the light gets in.|Ernest Hemingway"
  "That it will never come again is what makes life so sweet.|Emily Dickinson"
  "One day I will find the right words, and they will be simple.|Jack Kerouac"
  "There is no greater agony than bearing an untold story inside you.|Maya Angelou"
  "A bird doesn't sing because it has an answer, it sings because it has a song.|Maya Angelou"
  "Ask not what your country can do for you; ask what you can do for your country.|John F. Kennedy"
  "Nothing is certain except for death and taxes.|Benjamin Franklin"
  "Three can keep a secret, if two of them are dead.|Benjamin Franklin"
  "Well done is better than well said.|Benjamin Franklin"
  "Whatever you are, be a good one.|Abraham Lincoln"
  "No one can make you feel inferior without your consent.|Eleanor Roosevelt"
  "The only way to have a friend is to be one.|Ralph Waldo Emerson"
  "Imagination is everything. It is the preview of life's coming attractions.|Albert Einstein"
  "You don't write because you want to say something, you write because you have something to say.|F. Scott Fitzgerald"
  "The difference between the almost right word and the right word is the difference between the lightning bug and the lightning.|Mark Twain"
  "It is never too late to be what you might have been.|George Eliot"
  "Stay hungry, stay foolish.|Steve Jobs"
  "The people who are crazy enough to think they can change the world are the ones who do.|Steve Jobs"
  "Start writing, no matter what. The water does not flow until the faucet is turned on.|Louis L'Amour"
  "Freedom is never more than one generation away from extinction.|Ronald Reagan"
  "Information is the currency of democracy.|Thomas Jefferson"
  "I cannot live without books.|Thomas Jefferson"
  "The truest of all faces is the mask.|Walt Whitman"
  "I am large, I contain multitudes.|Walt Whitman"
  "Keep your face always toward the sunshine and shadows will fall behind you.|Walt Whitman"
  "The secret of getting ahead is getting started.|Mark Twain"
  "Logic will get you from A to B. Imagination will take you everywhere.|Albert Einstein"
  "Life is what happens when you're making other plans.|John Lennon"
  "Don't count the days, make the days count.|Muhammad Ali"
  "Truth is stranger than fiction.|Mark Twain"
  "A person who never made a mistake never tried anything new.|Albert Einstein"
  "Everything you've ever wanted is on the other side of fear.|George Addair"
  "Happiness is not something readymade. It comes from your own actions.|Dalai Lama"
  "Your time is limited, so don't waste it living someone else's life.|Steve Jobs"
  "Believe you can and you're halfway there.|Theodore Roosevelt"
  "Great thoughts speak only to the thoughtful mind, but great actions speak to all mankind.|Theodore Roosevelt"
  "The world is a book and those who do not travel read only one page.|St. Augustine"
  "It does not matter how slowly you go as long as you do not stop.|Confucius"
  # --- new entries ---
  "An unexamined life is not worth living.|Socrates"
  "Give me liberty, or give me death!|Patrick Henry"
  "That government is best which governs least.|Henry David Thoreau"
  "Go confidently in the direction of your dreams. Live the life you have imagined.|Henry David Thoreau"
  "Not all those who wander are lost.|J.R.R. Tolkien"
  "Do one thing every day that scares you.|Eleanor Roosevelt"
  "You must be the change you wish to see in the world.|Mahatma Gandhi"
  "We do not inherit the earth from our ancestors, we borrow it from our children.|Native American Proverb"
  "The only impossible journey is the one you never begin.|Tony Robbins"
  "It always seems impossible until it's done.|Nelson Mandela"
  "Darkness cannot drive out darkness; only light can do that.|Martin Luther King Jr."
  "Our lives begin to end the day we become silent about things that matter.|Martin Luther King Jr."
  "The time is always right to do what is right.|Martin Luther King Jr."
  "Float like a butterfly, sting like a bee.|Muhammad Ali"
  "Impossible is just a big word thrown around by small men.|Muhammad Ali"
  "A champion is defined not by their wins but by how they can recover when they fall.|Serena Williams"
  "You have to believe in yourself when no one else does.|Serena Williams"
  "The most courageous act is still to think for yourself. Aloud.|Coco Chanel"
  "I'm not afraid of storms, for I'm learning how to sail my ship.|Louisa May Alcott"
  "She is too fond of books, and it has turned her brain.|Louisa May Alcott"
  "Not until we are lost do we begin to find ourselves.|Henry David Thoreau"
  "Our greatest glory is not in never failing, but in rising every time we fail.|Ralph Waldo Emerson"
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.|Ralph Waldo Emerson"
  "Do not go where the path may lead, go instead where there is no path and leave a trail.|Ralph Waldo Emerson"
  "I took the road less traveled by, and that has made all the difference.|Robert Frost"
  "In three words I can sum up everything I've learned about life: it goes on.|Robert Frost"
  "Half the world is composed of people who have something to say and can't, and the other half who have nothing to say and keep on saying it.|Robert Frost"
  "The brain is wider than the sky.|Emily Dickinson"
  "Hope is the thing with feathers that perches in the soul.|Emily Dickinson"
  "I'm nobody! Who are you?|Emily Dickinson"
  "So we beat on, boats against the current, borne back ceaselessly into the past.|F. Scott Fitzgerald"
  "The test of a first-rate intelligence is the ability to hold two opposing ideas in mind at the same time.|F. Scott Fitzgerald"
  "On the road again, just can't wait to get on the road again.|Willie Nelson"
  "The future ain't what it used to be.|Yogi Berra"
  "It ain't over till it's over.|Yogi Berra"
  "When you come to a fork in the road, take it.|Yogi Berra"
  "Play like you're in first, train like you're in second.|Kobe Bryant"
  "The most important thing is to try and inspire people so that they can be great in whatever they want to do.|Kobe Bryant"
  "I've missed more than 9,000 shots in my career. I've lost almost 300 games. I've failed over and over and over again in my life. And that is why I succeed.|Michael Jordan"
  "Talent wins games, but teamwork and intelligence win championships.|Michael Jordan"
  "The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door to personal excellence.|Confucius"
  "You miss 100% of the shots you don't take.|Wayne Gretzky"
  "Hard work beats talent when talent doesn't work hard.|Tim Notke"
  "Whether you think you can or think you can't, you're right.|Henry Ford"
  "Coming together is a beginning, staying together is progress, and working together is success.|Henry Ford"
  "Innovation is seeing what everybody has seen and thinking what nobody has thought.|Dr. Albert Szent-Györgyi"
  "The greatest weapon against stress is our ability to choose one thought over another.|William James"
  "Act as if what you do makes a difference. It does.|William James"
  "Excellence is not a destination but a continuous journey that never ends.|Brian Tracy"
  "Either write something worth reading or do something worth writing.|Benjamin Franklin"
  "Energy and persistence conquer all things.|Benjamin Franklin"
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.|Benjamin Franklin"
  "We hold these truths to be self-evident, that all men are created equal.|Thomas Jefferson"
  "I like the dreams of the future better than the history of the past.|Thomas Jefferson"
  "Do you want to know who you are? Don't ask. Act! Action will delineate and define you.|Thomas Jefferson"
  "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.|Abraham Lincoln"
  "Character is like a tree and reputation its shadow. The shadow is what we think of it; the tree is the real thing.|Abraham Lincoln"
  "No man has a good enough memory to be a successful liar.|Abraham Lincoln"
  "Nearly all men can stand adversity, but if you want to test a man's character, give him power.|Abraham Lincoln"
  "Change your thoughts and you change your world.|Norman Vincent Peale"
  "Believe in yourself! Have faith in your abilities!|Norman Vincent Peale"
  "You are never too old to set another goal or to dream a new dream.|C.S. Lewis"
  "Hardships often prepare ordinary people for an extraordinary destiny.|C.S. Lewis"
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.|Brian Herbert"
  "Success usually comes to those who are too busy to be looking for it.|Henry David Thoreau"
  "If you want to lift yourself up, lift up someone else.|Booker T. Washington"
  "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.|Booker T. Washington"
  "I freed a thousand slaves. I could have freed a thousand more if only they knew they were slaves.|Harriet Tubman"
  "Every great dream begins with a dreamer.|Harriet Tubman"
  "One child, one teacher, one book, one pen can change the world.|Malala Yousafzai"
  "The secret of change is to focus all of your energy not on fighting the old, but on building the new.|Socrates"
  "Real courage is when you know you're licked before you begin, but you begin anyway.|Harper Lee"
  "You never really understand a person until you consider things from his point of view.|Harper Lee"
  "Not all readers are leaders, but all leaders are readers.|Harry S. Truman"
  "It is amazing what you can accomplish if you do not care who gets the credit.|Harry S. Truman"
  "The buck stops here.|Harry S. Truman"
  "The price of anything is the amount of life you exchange for it.|Henry David Thoreau"
  "Simplicity is the ultimate sophistication.|Leonardo da Vinci"
  "The journey of a thousand miles begins with one step.|Lao Tzu"
  "To infinity and beyond.|Buzz Lightyear"
  "Just keep swimming.|Dory"
  "With great power comes great responsibility.|Stan Lee"
  "In the middle of every difficulty lies opportunity.|Albert Einstein"
  "Try not to become a man of success, but rather try to become a man of value.|Albert Einstein"
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.|Albert Einstein"
  "The measure of intelligence is the ability to change.|Albert Einstein"
  "We cannot solve problems with the kind of thinking we employed when we came up with them.|Albert Einstein"
  "Anyone who has never made a mistake has never tried anything new.|Albert Einstein"
  "Education is what remains after one has forgotten what one has learned in school.|Albert Einstein"
  "Once you stop learning, you start dying.|Albert Einstein"
  "If you can't explain it simply, you don't understand it well enough.|Albert Einstein"
  "Life is like riding a bicycle. To keep your balance, you must keep moving.|Albert Einstein"
  "You only live once, but if you do it right, once is enough.|Mae West"
  "I never lose. I either win or learn.|Nelson Mandela"
  "The greatest glory in living lies not in never falling, but in rising every time we fall.|Nelson Mandela"
  "Do not judge me by my successes, judge me by how many times I fell down and got back up again.|Nelson Mandela"
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.|Mother Teresa"
  "If you judge people, you have no time to love them.|Mother Teresa"
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.|Bill Keane"
  "We must accept finite disappointment, but never lose infinite hope.|Martin Luther King Jr."
  "Injustice anywhere is a threat to justice everywhere.|Martin Luther King Jr."
  "The time is always right to do what is right.|Martin Luther King Jr."
  "Life is either a daring adventure or nothing at all.|Helen Keller"
  "Optimism is the faith that leads to achievement.|Helen Keller"
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.|Helen Keller"
  "Alone we can do so little; together we can do so much.|Helen Keller"
  "When one door of happiness closes, another opens.|Helen Keller"
  "Keep away from people who try to belittle your ambitions.|Mark Twain"
  "Courage is resistance to fear, mastery of fear — not absence of fear.|Mark Twain"
  "The secret of getting ahead is getting started.|Mark Twain"
  "Do the right thing. It will gratify some people and astonish the rest.|Mark Twain"
  "Never put off till tomorrow what may be done the day after tomorrow just as well.|Mark Twain"
  "Good friends, good books, and a sleepy conscience: this is the ideal life.|Mark Twain"
  "Kindness is the language which the deaf can hear and the blind can see.|Mark Twain"
  "The two most important days in your life are the day you are born and the day you find out why.|Mark Twain"
  "We are all apprentices in a craft where no one ever becomes a master.|Ernest Hemingway"
  "The best way to find out if you can trust somebody is to trust them.|Ernest Hemingway"
  "There is nothing to writing. All you do is sit down at a typewriter and bleed.|Ernest Hemingway"
  "Courage is grace under pressure.|Ernest Hemingway"
  "The world breaks everyone, and afterward, some are strong at the broken places.|Ernest Hemingway"
  "There is no friend as loyal as a book.|Ernest Hemingway"
  "So it goes.|Kurt Vonnegut"
  "We are what we pretend to be, so we must be careful about what we pretend to be.|Kurt Vonnegut"
  "I want to stand as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.|Kurt Vonnegut"
  "Of all the words of mice and men, the saddest are, 'It might have been.'|Kurt Vonnegut"
  "The truth will set you free, but first it will make you miserable.|James A. Garfield"
  "Be yourself; everyone else is already taken.|Oscar Wilde"
  "To live is the rarest thing in the world. Most people just exist.|Oscar Wilde"
  "I am so clever that sometimes I don't understand a single word of what I am saying.|Oscar Wilde"
  "Experience is simply the name we give our mistakes.|Oscar Wilde"
  "Always forgive your enemies — nothing annoys them so much.|Oscar Wilde"
  "A good friend will always stab you in the front.|Oscar Wilde"
  "Memory is the diary we all carry about with us.|Oscar Wilde"
  "The only way to get rid of a temptation is to yield to it.|Oscar Wilde"
  "We are all in the gutter, but some of us are looking at the stars.|Oscar Wilde"
  "What you do speaks so loudly that I cannot hear what you say.|Ralph Waldo Emerson"
  "Nothing great was ever achieved without enthusiasm.|Ralph Waldo Emerson"
  "For every minute you are angry you lose sixty seconds of happiness.|Ralph Waldo Emerson"
  "Write it on your heart that every day is the best day in the year.|Ralph Waldo Emerson"
  "The creation of something new is not accomplished by the intellect but by the play instinct.|Carl Jung"
  "Your vision will become clear only when you can look into your own heart.|Carl Jung"
  "Until you make the unconscious conscious, it will direct your life and you will call it fate.|Carl Jung"
  "Show me a man with a tattoo and I'll show you a man with an interesting past.|Jack London"
  "You can't wait for inspiration. You have to go after it with a club.|Jack London"
  "The proper function of man is to live, not to exist.|Jack London"
  "I would rather be ashes than dust.|Jack London"
  "It is better to light a candle than curse the darkness.|Eleanor Roosevelt"
  "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.|Eleanor Roosevelt"
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.|Eleanor Roosevelt"
  "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.|Eleanor Roosevelt"
  "With the new day comes new strength and new thoughts.|Eleanor Roosevelt"
  "A woman is like a tea bag — you never know how strong she is until she gets in hot water.|Eleanor Roosevelt"
  "Well-behaved women seldom make history.|Laurel Thatcher Ulrich"
  "I am not afraid of storms, for I am learning how to sail my ship.|Louisa May Alcott"
  "I am not what happened to me, I am what I choose to become.|Carl Jung"
  "Science is not only a disciple of reason but also one of romance and passion.|Stephen Hawking"
  "However difficult life may seem, there is always something you can do and succeed at.|Stephen Hawking"
  "Intelligence is the ability to adapt to change.|Stephen Hawking"
  "We are just an advanced breed of monkeys on a minor planet of a very average star.|Stephen Hawking"
  "Look up at the stars and not down at your feet.|Stephen Hawking"
  "My goal is simple. It is a complete understanding of the universe.|Stephen Hawking"
  "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.|Stephen Hawking"
  "One of the basic rules of the universe is that nothing is perfect. Perfection simply doesn't exist.|Stephen Hawking"
  "Not all those who wander are lost.|J.R.R. Tolkien"
  "All that is gold does not glitter.|J.R.R. Tolkien"
  "Even the smallest person can change the course of the future.|J.R.R. Tolkien"
  "If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.|J.R.R. Tolkien"
  "Faithless is he that says farewell when the road darkens.|J.R.R. Tolkien"
  "It's the job that's never started as takes longest to finish.|J.R.R. Tolkien"
  "Speak the truth, even if your voice shakes.|Maggie Kuhn"
  "The most common form of despair is not being who you are.|Søren Kierkegaard"
  "He who has a why to live can bear almost any how.|Friedrich Nietzsche"
  "Without music, life would be a mistake.|Friedrich Nietzsche"
  "That which does not kill us makes us stronger.|Friedrich Nietzsche"
  "In individuals, insanity is rare; but in groups, parties, nations, and epochs, it is the rule.|Friedrich Nietzsche"
  "The secret for harvesting from existence the greatest fruitfulness and the greatest enjoyment is to live dangerously.|Friedrich Nietzsche"
  "We should consider every day lost on which we have not danced at least once.|Friedrich Nietzsche"
  "You must have chaos within you to give birth to a dancing star.|Friedrich Nietzsche"
  "God is dead. God remains dead. And we have killed him.|Friedrich Nietzsche"
  "The higher we soar, the smaller we appear to those who cannot fly.|Friedrich Nietzsche"
  "There are no facts, only interpretations.|Friedrich Nietzsche"
  "To live is to suffer, to survive is to find some meaning in the suffering.|Friedrich Nietzsche"
  "Art is not what you see, but what you make others see.|Edgar Degas"
  "Creativity takes courage.|Henri Matisse"
  "Every child is an artist. The problem is how to remain an artist once we grow up.|Pablo Picasso"
  "The purpose of art is washing the dust of daily life off our souls.|Pablo Picasso"
  "Learn the rules like a pro, so you can break them like an artist.|Pablo Picasso"
  "Action is the foundational key to all success.|Pablo Picasso"
  "Only put off until tomorrow what you are willing to die having left undone.|Pablo Picasso"
  "The meaning of life is to find your gift. The purpose of life is to give it away.|Pablo Picasso"
  "Inspiration exists, but it has to find you working.|Pablo Picasso"
  "Everything you can imagine is real.|Pablo Picasso"
  "Good judgment comes from experience, and experience comes from bad judgment.|Rita Mae Brown"
  "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.|Sylvia Plath"
  "I am not sad, he would say. I am not sad, as if he were trying to convince himself.|Jonathan Safran Foer"
  "Not all readers are leaders, but all leaders are readers.|Harry S. Truman"
  "It is not length of life, but depth of life.|Ralph Waldo Emerson"
  "Do not go gentle into that good night.|Dylan Thomas"
  "Rage, rage against the dying of the light.|Dylan Thomas"
  "The only way out of the labyrinth of suffering is to forgive.|John Green"
  "What is the point of being alive if you don't at least try to do something remarkable?|John Green"
  "Some infinities are bigger than other infinities.|John Green"
  "Maybe our favorite quotations say more about us than about the stories and people we're quoting.|John Green"
  "The truth is rarely pure and never simple.|Oscar Wilde"
  "We accept the love we think we deserve.|Stephen Chbosky"
  "And in that moment, I swear we were infinite.|Stephen Chbosky"
  "Things change. And friends leave. Life doesn't stop for anybody.|Stephen Chbosky"
  "Try to be a rainbow in someone's cloud.|Maya Angelou"
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.|Maya Angelou"
  "My mission in life is not merely to survive, but to thrive.|Maya Angelou"
  "You may not control all the events that happen to you, but you can decide not to be reduced by them.|Maya Angelou"
  "Nothing will work unless you do.|Maya Angelou"
  "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.|Maya Angelou"
  "If you don't like something, change it. If you can't change it, change your attitude.|Maya Angelou"
  "You alone are enough. You have nothing to prove to anybody.|Maya Angelou"
  "When someone shows you who they are, believe them the first time.|Maya Angelou"
  "Success is liking yourself, liking what you do, and liking how you do it.|Maya Angelou"
  "Prejudice is a burden that confuses the past, threatens the future, and renders the present inaccessible.|Maya Angelou"
  "I love to see a young girl go out and grab the world by the lapels.|Maya Angelou"
  "We need much less than we think we need.|Maya Angelou"
  "My life has been one great big joke, a dance that's walked a song that's spoke.|Maya Angelou"
  "History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.|Maya Angelou"
  "If you are always trying to be normal, you will never know how amazing you can be.|Maya Angelou"
  "There is no greater agony than bearing an untold story inside you.|Maya Angelou"
  "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.|Maya Angelou"
  "The ache for home lives in all of us, the safe place where we can go as we are and not be judged.|Maya Angelou"
  "I can be changed by what happens to me. But I refuse to be reduced by it.|Maya Angelou"
)
